# Generating cutflow spreadsheets
Analysis algorithms often print out the cutflow table to the terminal.

The accompanying file `cutflow_funcs.py` creates some simple functions to achieve some basic goals:
1. Extract a cutflow string from a text file.
2. Convert an extracted string to a DF.
3. Manipulate the DF (add columns, change column names, etc.)
4. Save DFs to a spreadsheet.

This notebook is meant as a playground to use these functions on real cutflows.

Section 1 gives in an example use of the functions.

NOTE: analyses often use different cutflow formats - you may have to define your own extraction and conversion functions.

Imports

In [15]:
# Standard libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Import custom functions
import re
import importlib
imported_module = importlib.import_module("cutflow_funcs")
importlib.reload(imported_module)

# Help check you are using the latest version
import cutflow_funcs as cf
cf.test_func()

2.1

***
## 1. Example use - DO NOT CHANGE
***
Demonstration of the functions on cutflows in the ZdZdPostProcessing format.

In [34]:
# Examples
cutflow_dir = '/Users/matt/Documents/work/0-PhD/particle/xxzx-analysis/code_ZdZd/cutflows/'

### 1.1 ZdZdPostProcessing cutflows

In [52]:
# File of ZdZdPP cutflows
zdzdPP_cutflows_2026_02 = '2026-02-09_ZdZdPP-cutflows.txt'

# Extract from the file
zdzdPP_cutflow_dict = cf.parse_ZdZdPP_cutflow_file(cutflow_dir + zdzdPP_cutflows_2026_02)

# Save DFs using a dictionary comprehension
zdzdPP_cutflow_dfs = {name: cf.simplify_ZdZdPP_cutflow(cf.str_to_df_ZdZdPP(cutflow))
                      for name, cutflow in zdzdPP_cutflow_dict.items()}
# Save to spreadsheet
# cf.make_spreadsheet(cutflow_dir+'2026-02-14_ZdZdPP-cutflows.xlsx', zdzdPP_cutflow_dfs)

# cf.simplify_ZdZdPP_cutflow(cf.str_to_df_ZdZdPP(zdzdPP_cutflow_dict['mc23a_zd30']))
# display(zdzdPP_cutflow_dfs['mc23a_zd30'])

# Print the data types of the columns in the cutflow dataframe
print(zdzdPP_cutflow_dfs['mc23a_zd30'].dtypes)

Cuts             object
weights_4e      float64
events_4e         int64
weights_2e2m    float64
events_2e2m       int64
weights_4m      float64
events_4m         int64
weights_All     float64
events_All        int64
dtype: object

### 1.2 Scott's cutflows

In [11]:
# File of Scott's cutflows
scott_cutflows_2025_10 = '2025-10-17_Scott-ZdZd-R3-cutflows.txt'
# Extract from the file
scotts_cutflow_dict = cf.parse_Scott_cutflow_file(cutflow_dir + scott_cutflows_2025_10)
# Save DFs using a dictionary comprehension
scotts_cutflow_dfs = {name.replace(' --- ', '_'): cf.str_to_df_Scott(cutflow)
                      for name, cutflow in scotts_cutflow_dict.items()}
# Save to spreadsheet
# make_spreadsheet('test4.xlsx', scotts_cutflow_dfs)

scotts_cutflow_dfs['zd5_23a_reco']

                 Cut  N4e    Wt4e   Nem    Wtem   N4m    Wt4m  N all  Wt all
0             weight                                           22846  0.0000
1            overlap                                           22846  0.0000
2              clean                                           22846  0.0000
3                 pv                                           22846  0.0000
4            trigger                                           19443  0.0000
5           jetclean                                           19443  0.0000
6   *Quad selection*
7          quad sfos                                           19104  0.0000
8            quad or                                           19103  0.0000
9           quad kin                                           18378  0.0000
10    quad trigmatch                                           18102  0.0000
11           quad dr                                           16560  0.0000
12          *Common*
13              isol  219  0.0000  2648  0.0000  5761  0.0000   8628  0.0000
14              e_id  219  0.0000  2648  0.0000  5761  0.0000   8628  0.0000
15            impact  219  0.0000  2597  0.0000  5605  0.0000   8421  0.0000
16              jpsi  216  0.0000  2576  0.0000  5546  0.0000   8338  0.0000
17           upsilon  216  0.0000  2576  0.0000  5546  0.0000   8338  0.0000
18          lowmveto   65  0.0000   612  0.0000   958  0.0000   1635  0.0000
19              *HM*
20             hwind   49  0.0000   517  0.0000   932  0.0000   1498  0.0000
21             zveto   28  0.0000   517  0.0000   494  0.0000   1039  0.0000
22             loose    0       0     0       0     0       0      0       0
23            medium    0       0     0       0     0       0      0       0
24             tight    0       0     0       0     0       0      0       0
25          *AS SR1*
26               SR1    0       0     0       0     0       0      0       0
27             zveto    0       0     0       0     0       0      0       0
28             loose    0       0     0       0     0       0      0       0
29            medium    0       0     0       0     0       0      0       0
30             tight    0       0     0       0     0       0      0       0
31          *AS SR2*
32               SR2   16  0.0000    95  0.0000    26  0.0000    137  0.0000
33             zveto   15  0.0000    95  0.0000    21  0.0000    131  0.0000
34             loose    0       0     0       0     0       0      0       0
35            medium    0       0     0       0     0       0      0       0
36             tight    0       0     0       0     0       0      0       0

***
## 2. Your code here!
***

In [13]:
# Path to the cutflow files

# Extract the cutflow data from the files

# Convert the cutflow data into DataFrames

# Manipulate the DataFrames as needed (e.g., simplify, calculate efficiencies)

# Save the DataFrames to a spreadsheet

***
## 3. Scott's cutflows vs. ZdZdPostProcessing
***

Fixing ZdZdPP

In [58]:
new_col_order = ['Cuts', 'events_4e', 'weights_4e', 'events_2e2m', 'weights_2e2m', 'events_4m', 'weights_4m', 'events_All', 'weights_All']

zdzdPP_cutflow_dfs_copy = zdzdPP_cutflow_dfs.copy()

# Drop rows where the value of 'Cut' is 'MuType'
for name, df in zdzdPP_cutflow_dfs_copy.items():
    zdzdPP_cutflow_dfs_copy[name] = df[df['Cuts'] != 'MuType'].reset_index(drop=True, inplace=False).replace(0, np.nan)[new_col_order]

# zdzdPP_cutflow_dfs_copy['mc23e_zd30'].reset_index(drop=True, inplace=True)
zdzdPP_cutflow_dfs_copy['mc23a_zd30'].columns
# Reorder the columns in the DataFrame
# for name, df in zdzdPP_cutflow_dfs_copy.items():
#     zdzdPP_cutflow_dfs_copy[name] = df[new_col_order]

zdzdPP_cutflow_dfs_copy['mc23d_zd30']

# Save to spreadsheet
cf.make_spreadsheet(cutflow_dir+'2026-02-17_ZdZdPP-cutflows.xlsx', zdzdPP_cutflow_dfs_copy)

Fixing Scott's cutflows

In [ ]:
simplify_Scott_cutflow(scotts_cutflow_dfs['zd30_23a_reco'], new_col_order)

# scotts_cutflow_dfs['zd30_23d_reco'].columns = new_col_order
scotts_cutflow_dfs['zd30_23d_reco']

,Cuts,events_4e,weights_4e,events_2e2m,weights_2e2m,events_4m,weights_4m,events_All,weights_All
0,weight,,,,,,,50000,0.0000
1,overlap,,,,,,,50000,0.0000
2,clean,,,,,,,50000,0.0000
3,pv,,,,,,,50000,0.0000
4,trigger,,,,,,,38800,0.0000
5,jetclean,,,,,,,38459,0.0000
6,*Quad selection*,,,,,,,,
7,quad sfos,,,,,,,17306,0.0000
8,quad or,,,,,,,17302,0.0000
9,quad kin,,,,,,,16830,0.0000
10,quad trigmatch,,,,,,,16751,0.0000
11,quad dr,,,,,,,16728,0.0000
12,*Common*,,,,,,,,
13,isol,1820,0.0000,6509,0.0000,5376,0.0000,13705,0.0000
14,e_id,1820,0.0000,6509,0.0000,5376,0.0000,13705,0.0000
15,impact,1798,0.0000,6360,0.0000,5200,0.0000,13358,0.0000
16,jpsi,1798,0.0000,6360,0.0000,5198,0.0000,13356,0.0000
17,upsilon,1795,0.0000,6355,0.0000,5187,0.0000,13337,0.0000
18,lowmveto,1795,0.0000,6355,0.0000,5185,0.0000,13335,0.0000
19,*HM*,,,,,,,,
20,hwind,1557,0.0000,5844,0.0000,4978,0.0000,12379,0.0000
21,zveto,1073,0.0000,5844,0.0000,3391,0.0000,10308,0.0000
22,loose,1070,0.0000,5836,0.0000,3361,0.0000,10267,0.0000
23,medium,1066,0.0000,5809,0.0000,3353,0.0000,10228,0.0000
24,tight,305,0.0000,1755,0.0000,1222,0.0000,3282,0.0000
25,*AS SR1*,,,,,,,,
26,SR1,71,0.0000,233,0.0000,173,0.0000,477,0.0000
27,zveto,68,0.0000,233,0.0000,160,0.0000,461,0.0000
28,loose,62,0.0000,197,0.0000,117,0.0000,376,0.0000
29,medium,52,0.0000,136,0.0000,87,0.0000,275,0.0000
30,tight,23,0.0000,58,0.0000,27,0.0000,108,0.0000
31,*AS SR2*,,,,,,,,
32,SR2,167,0.0000,278,0.0000,34,0.0000,479,0.0000
33,zveto,151,0.0000,278,0.0000,28,0.0000,457,0.0000
34,loose,147,0.0000,278,0.0000,26,0.0000,451,0.0000
35,medium,137,0.0000,262,0.0000,26,0.0000,425,0.0000
36,tight,106,0.0000,201,0.0000,26,0.0000,333,0.0000

In [29]:
scott_copy = scotts_cutflow_dfs.copy()
# Remove all rows from scott_copy['zd30_23d_reco'] where the value of 'Cut' contains 'overlap', 'jpsi' or '*'
# test_scott_df = scott_copy['zd30_23d_reco'][~scott_copy['zd30_23d_reco']['Cut'].str.contains('overlap|jpsi|\*', case=False, regex=True)]
# Find the index of the row where the value of 'Cut' is '*AS SR1*'
test_scott_df = scott_copy['zd30_23d_reco'][scott_copy['zd30_23d_reco']['Cut'] == '*AS SR1*']
test_scott_df.index
# Get the subset of the df up until this index
test_scott_df_subset = scott_copy['zd30_23d_reco'].iloc[:test_scott_df.index[0]]
test_scott_df_subset

# new_scott_df = {}
# for name, df in scotts_cutflow_dfs.items():
#     new_scott_df[name] = df[~df['Cut'].str.contains('overlap|jpsi|\*', case=False, regex=True)]

                 Cut   N4e    Wt4e   Nem    Wtem   N4m    Wt4m  N all  Wt all
0             weight                                            50000  0.0000
1            overlap                                            50000  0.0000
2              clean                                            50000  0.0000
3                 pv                                            50000  0.0000
4            trigger                                            38800  0.0000
5           jetclean                                            38459  0.0000
6   *Quad selection*
7          quad sfos                                            17306  0.0000
8            quad or                                            17302  0.0000
9           quad kin                                            16830  0.0000
10    quad trigmatch                                            16751  0.0000
11           quad dr                                            16728  0.0000
12          *Common*
13              isol  1820  0.0000  6509  0.0000  5376  0.0000  13705  0.0000
14              e_id  1820  0.0000  6509  0.0000  5376  0.0000  13705  0.0000
15            impact  1798  0.0000  6360  0.0000  5200  0.0000  13358  0.0000
16              jpsi  1798  0.0000  6360  0.0000  5198  0.0000  13356  0.0000
17           upsilon  1795  0.0000  6355  0.0000  5187  0.0000  13337  0.0000
18          lowmveto  1795  0.0000  6355  0.0000  5185  0.0000  13335  0.0000
19              *HM*
20             hwind  1557  0.0000  5844  0.0000  4978  0.0000  12379  0.0000
21             zveto  1073  0.0000  5844  0.0000  3391  0.0000  10308  0.0000
22             loose  1070  0.0000  5836  0.0000  3361  0.0000  10267  0.0000
23            medium  1066  0.0000  5809  0.0000  3353  0.0000  10228  0.0000
24             tight   305  0.0000  1755  0.0000  1222  0.0000   3282  0.0000

## 4. Scott's cutflows - updated

2026-02-17: Removed jet cleaning, added weights and added scale factors for R3 electrons.

In [4]:
new_mc23a_zd30 = '''|                 |N4e  |Wt4e   |Nem  |Wtem   |N4m  |Wt4m   |N all |Wt all |
|*Precuts*                                                         |||||||||
|weight           |     |       |     |       |     |       |60000 |60000  |
|overlap          |     |       |     |       |     |       |60000 |60000  |
|clean            |     |       |     |       |     |       |60000 |60000  |
|pv               |     |       |     |       |     |       |60000 |60000  |
|trigger          |     |       |     |       |     |       |51707 |51714  |
|*Quad selection*                                                  |||||||||
|quad sfos        |     |       |     |       |     |       |23636 |23684  |
|quad or          |     |       |     |       |     |       |23606 |23654  |
|quad kin         |     |       |     |       |     |       |22900 |22942  |
|quad trigmatch   |     |       |     |       |     |       |22768 |22808  |
|quad dr          |     |       |     |       |     |       |22736 |22776  |
|*Common*                                                          |||||||||
|isol             |3010 |2846.8 |8948 |8351.4 |6954 |6366.6 |18912 |17565  |
|e_id             |3010 |2846.8 |8948 |8351.4 |6954 |6366.6 |18912 |17565  |
|impact           |2990 |2828.7 |8763 |8180.8 |6750 |6179.1 |18503 |17189  |
|jpsi             |2990 |2828.7 |8762 |8179.8 |6749 |6178.2 |18501 |17187  |
|upsilon          |2986 |2825.6 |8761 |8178.7 |6725 |6156.1 |18472 |17160  |
|lowmveto         |2986 |2825.6 |8759 |8177.1 |6724 |6155.1 |18469 |17158  |
|*HM*                                                              |||||||||
|hwind            |2601 |2459.1 |8032 |7492.0 |6456 |5908.2 |17089 |15859  |
|zveto            |1817 |1715.3 |8032 |7492.0 |4359 |3997.3 |14208 |13205  |
|loose            |1810 |1708.8 |8023 |7483.7 |4326 |3967.1 |14159 |13160  |
|medium           |1802 |1701.3 |7992 |7456.3 |4321 |3963.1 |14115 |13121  |
|tight            |521  |495.68 |2390 |2244.0 |1557 |1425.7 |4468  |4165.4 |
|*AS SR1*                                                          |||||||||
|SR1              |114  |109.50 |331  |312.00 |228  |209.87 |673   |631.37 |
|zveto            |108  |104.42 |331  |312.00 |210  |193.52 |649   |609.95 |
|loose            |90   |87.371 |275  |259.23 |169  |155.20 |534   |501.80 |
|medium           |69   |67.340 |204  |191.25 |123  |116.28 |396   |374.87 |
|tight            |39   |37.843 |71   |67.378 |46   |44.507 |156   |149.73 |
|*AS SR2*                                                          |||||||||
|SR2              |271  |256.96 |396  |373.15 |40   |37.030 |707   |667.14 |
|zveto            |244  |229.96 |396  |373.15 |38   |34.896 |678   |638.00 |
|loose            |242  |228.09 |396  |373.15 |37   |34.382 |675   |635.62 |
|medium           |224  |211.05 |364  |344.73 |37   |34.382 |625   |590.16 |
|tight            |182  |172.51 |279  |265.27 |37   |34.382 |498   |472.17 |'''

In [6]:
new_mc23a_zd30_df = cf.str_to_df_Scott(new_mc23a_zd30)
new_mc23a_zd30_df

                 Cut   N4e    Wt4e   Nem    Wtem   N4m    Wt4m  N all  Wt all
0             weight                                            60000   60000
1            overlap                                            60000   60000
2              clean                                            60000   60000
3                 pv                                            60000   60000
4            trigger                                            51707   51714
5   *Quad selection*
6          quad sfos                                            23636   23684
7            quad or                                            23606   23654
8           quad kin                                            22900   22942
9     quad trigmatch                                            22768   22808
10           quad dr                                            22736   22776
11          *Common*
12              isol  3010  2846.8  8948  8351.4  6954  6366.6  18912   17565
13              e_id  3010  2846.8  8948  8351.4  6954  6366.6  18912   17565
14            impact  2990  2828.7  8763  8180.8  6750  6179.1  18503   17189
15              jpsi  2990  2828.7  8762  8179.8  6749  6178.2  18501   17187
16           upsilon  2986  2825.6  8761  8178.7  6725  6156.1  18472   17160
17          lowmveto  2986  2825.6  8759  8177.1  6724  6155.1  18469   17158
18              *HM*
19             hwind  2601  2459.1  8032  7492.0  6456  5908.2  17089   15859
20             zveto  1817  1715.3  8032  7492.0  4359  3997.3  14208   13205
21             loose  1810  1708.8  8023  7483.7  4326  3967.1  14159   13160
22            medium  1802  1701.3  7992  7456.3  4321  3963.1  14115   13121
23             tight   521  495.68  2390  2244.0  1557  1425.7   4468  4165.4
24          *AS SR1*
25               SR1   114  109.50   331  312.00   228  209.87    673  631.37
26             zveto   108  104.42   331  312.00   210  193.52    649  609.95
27             loose    90  87.371   275  259.23   169  155.20    534  501.80
28            medium    69  67.340   204  191.25   123  116.28    396  374.87
29             tight    39  37.843    71  67.378    46  44.507    156  149.73
30          *AS SR2*
31               SR2   271  256.96   396  373.15    40  37.030    707  667.14
32             zveto   244  229.96   396  373.15    38  34.896    678  638.00
33             loose   242  228.09   396  373.15    37  34.382    675  635.62
34            medium   224  211.05   364  344.73    37  34.382    625  590.16
35             tight   182  172.51   279  265.27    37  34.382    498  472.17

In [10]:
cf.make_spreadsheet(cutflow_dir + 'test5.xlsx', {'new_mc23a_zd30': new_mc23a_zd30_df})

## 5. ZdZdPP - testing new medium SR cut
2026-02-23: implemented new SR cut in the code, need to check if it made a difference.

In [3]:
test_ZdZdPP_mc23a_zd30_oldMSR = '''|               |#==561511           |#==5615111        |#==5615112          |#==5615113        |
-------------------------------------------------------------------------------------------------
|All            |60000.000000 (60000)|0.000000 (0)      |0.000000 (0)        |0.000000 (0)      |
|Cleaning       |60000.000000 (60000)|0.000000 (0)      |0.000000 (0)        |0.000000 (0)      |
|PrimaryVertex  |60000.000000 (60000)|0.000000 (0)      |0.000000 (0)        |0.000000 (0)      |
|Trigger        |51707.000000 (51707)|0.000000 (0)      |0.000000 (0)        |0.000000 (0)      |
|SFOS           |0.000000 (0)        |3760.000000 (3760)|10682.352539 (11016)|7722.914062 (8217)|
|NotOverlaps    |0.000000 (0)        |3760.000000 (3760)|10676.549805 (11010)|7722.914062 (8217)|
|Kinematic      |0.000000 (0)        |3709.000000 (3709)|10407.008789 (10732)|7404.216309 (7878)|
|TriggerMatched |0.000000 (0)        |3676.000000 (3676)|10351.664062 (10675)|7370.417969 (7842)|
|MuType         |0.000000 (0)        |3682.000000 (3682)|10351.674805 (10675)|7367.432129 (7839)|
|DeltaR         |0.000000 (0)        |3671.000000 (3671)|10330.267578 (10653)|7356.226562 (7827)|
|Isolation      |0.000000 (0)        |3010.000000 (3010)|8509.522461 (8775)  |6233.960449 (6634)|
|ElectronID     |0.000000 (0)        |3010.000000 (3010)|8509.522461 (8775)  |6233.960449 (6634)|
|ImpactParameter|0.000000 (0)        |2999.000000 (2999)|8366.896484 (8628)  |6065.047363 (6454)|
|Jpsi           |0.000000 (0)        |2999.000000 (2999)|8365.930664 (8627)  |6064.151367 (6453)|
|Upsilon        |0.000000 (0)        |2995.000000 (2995)|8364.972656 (8626)  |6045.185059 (6433)|
|LowMassVeto    |0.000000 (0)        |2995.000000 (2995)|8363.064453 (8624)  |6044.229980 (6432)|
|HWindow        |0.000000 (0)        |2607.000000 (2607)|7669.435547 (7908)  |5803.901855 (6176)|
|ZVeto          |0.000000 (0)        |1833.000000 (1833)|7669.435547 (7908)  |3926.846924 (4179)|
|LooseSR        |0.000000 (0)        |1833.000000 (1833)|7669.435547 (7908)  |3926.846924 (4179)|
|MediumSR       |0.000000 (0)        |1760.000000 (1760)|7517.316406 (7751)  |3897.685547 (4148)|
-------------------------------------------------------------------------------------------------'''

test_ZdZdPP_mc23a_zd30_newMSR = '''|               |#==561511           |#==5615111        |#==5615112          |#==5615113        |
-------------------------------------------------------------------------------------------------
|All            |60000.000000 (60000)|0.000000 (0)      |0.000000 (0)        |0.000000 (0)      |
|Cleaning       |60000.000000 (60000)|0.000000 (0)      |0.000000 (0)        |0.000000 (0)      |
|PrimaryVertex  |60000.000000 (60000)|0.000000 (0)      |0.000000 (0)        |0.000000 (0)      |
|Trigger        |51707.000000 (51707)|0.000000 (0)      |0.000000 (0)        |0.000000 (0)      |
|SFOS           |0.000000 (0)        |3760.000000 (3760)|10682.352539 (11016)|7722.914062 (8217)|
|NotOverlaps    |0.000000 (0)        |3760.000000 (3760)|10676.549805 (11010)|7722.914062 (8217)|
|Kinematic      |0.000000 (0)        |3709.000000 (3709)|10407.008789 (10732)|7404.216309 (7878)|
|TriggerMatched |0.000000 (0)        |3676.000000 (3676)|10351.664062 (10675)|7370.417969 (7842)|
|MuType         |0.000000 (0)        |3682.000000 (3682)|10351.674805 (10675)|7367.432129 (7839)|
|DeltaR         |0.000000 (0)        |3671.000000 (3671)|10330.267578 (10653)|7356.226562 (7827)|
|Isolation      |0.000000 (0)        |3010.000000 (3010)|8509.522461 (8775)  |6233.960449 (6634)|
|ElectronID     |0.000000 (0)        |3010.000000 (3010)|8509.522461 (8775)  |6233.960449 (6634)|
|ImpactParameter|0.000000 (0)        |2999.000000 (2999)|8366.896484 (8628)  |6065.047363 (6454)|
|Jpsi           |0.000000 (0)        |2999.000000 (2999)|8365.930664 (8627)  |6064.151367 (6453)|
|Upsilon        |0.000000 (0)        |2995.000000 (2995)|8364.972656 (8626)  |6045.185059 (6433)|
|LowMassVeto    |0.000000 (0)        |2995.000000 (2995)|8363.064453 (8624)  |6044.229980 (6432)|
|HWindow        |0.000000 (0)        |2607.000000 (2607)|7669.435547 (7908)  |5803.901855 (6176)|
|ZVeto          |0.000000 (0)        |1833.000000 (1833)|7669.435547 (7908)  |3926.846924 (4179)|
|LooseSR        |0.000000 (0)        |1833.000000 (1833)|7669.435547 (7908)  |3926.846924 (4179)|
|MediumSR       |0.000000 (0)        |1760.000000 (1760)|7517.316406 (7751)  |3897.685547 (4148)|
-------------------------------------------------------------------------------------------------'''

## 6. New Ntuples
Scott updated the ZdZd13TeV to incorporate some new things (e.g. baseline z0sintheta cut and electron SFs for Run 3 AF3).

We created new Ntuples to test the cutflows on.

In [43]:
# Scott updated the ZdZd13TeV code on 2026-23-02: the following strings with 'newNtuple' in the name use this new cutflow:

# The cutflow Scott emailed on 2026-23-02
scott_newNtuple_str = '''|                 |N4e  |Wt4e   |Nem  |Wtem   |N4m  |Wt4m   |N all |Wt all |
|*Precuts*                                                         |||||||||
|weight           |     |       |     |       |     |       |60000 |60000  |
|overlap          |     |       |     |       |     |       |60000 |60000  |
|clean            |     |       |     |       |     |       |60000 |60000  |
|pv               |     |       |     |       |     |       |60000 |60000  |
|trigger          |     |       |     |       |     |       |51707 |51714  |
|*Quad selection*                                                  |||||||||
|quad sfos        |     |       |     |       |     |       |23516 |23565  |
|quad or          |     |       |     |       |     |       |23488 |23538  |
|quad kin         |     |       |     |       |     |       |22796 |22840  |
|quad trigmatch   |     |       |     |       |     |       |22666 |22708  |
|quad dr          |     |       |     |       |     |       |22634 |22676  |
|quad mqual       |     |       |     |       |     |       |22616 |22659  |
|*Common*                                                          |||||||||
|isol             |3004 |2841.4 |8909 |8315.0 |6934 |6350.3 |18847 |17507  |
|e_id             |3004 |2841.4 |8909 |8315.0 |6934 |6350.3 |18847 |17507  |
|impact           |2993 |2831.0 |8767 |8184.5 |6751 |6180.3 |18511 |17196  |
|jpsi             |2993 |2831.0 |8766 |8183.5 |6750 |6179.5 |18509 |17194  |
|upsilon          |2989 |2827.9 |8765 |8182.4 |6726 |6157.3 |18480 |17168  |
|lowmveto         |2989 |2827.9 |8763 |8180.9 |6725 |6156.4 |18477 |17165  |
|*HM*                                                              |||||||||
|hwind            |2604 |2461.5 |8034 |7494.4 |6457 |5909.5 |17095 |15865  |
|zveto            |1819 |1717.3 |8034 |7494.4 |4359 |3997.3 |14212 |13209  |
|loose            |1812 |1710.8 |8025 |7486.1 |4326 |3967.1 |14163 |13164  |
|medium           |1804 |1703.2 |7994 |7458.7 |4321 |3963.1 |14119 |13125  |
|tight            |521  |495.68 |2391 |2245.3 |1557 |1425.7 |4469  |4166.7 |
|*AS SR1*                                                          |||||||||
|SR1              |114  |109.50 |333  |313.36 |228  |209.87 |675   |632.73 |
|zveto            |108  |104.42 |333  |313.36 |210  |193.52 |651   |611.31 |
|loose            |90   |87.371 |277  |260.59 |169  |155.20 |536   |503.16 |
|medium           |69   |67.340 |206  |192.61 |123  |116.28 |398   |376.23 |
|tight            |39   |37.843 |71   |67.378 |46   |44.507 |156   |149.73 |
|*AS SR2*                                                          |||||||||
|SR2              |271  |256.96 |396  |373.15 |40   |37.030 |707   |667.14 |
|zveto            |244  |229.96 |396  |373.15 |38   |34.896 |678   |638.00 |
|loose            |242  |228.09 |396  |373.15 |37   |34.382 |675   |635.62 |
|medium           |224  |211.05 |364  |344.73 |37   |34.382 |625   |590.16 |
|tight            |182  |172.51 |279  |265.27 |37   |34.382 |498   |472.17 |'''

# Result of ZdZdPP cutflow using the old Medium SR cut
zdzdPP_newNtuple_oldMSR_str = '''|               |#==561511           |#==5615111        |#==5615112          |#==5615113        |
-------------------------------------------------------------------------------------------------
|All            |60000.000000 (60000)|0.000000 (0)      |0.000000 (0)        |0.000000 (0)      |
|Cleaning       |60000.000000 (60000)|0.000000 (0)      |0.000000 (0)        |0.000000 (0)      |
|PrimaryVertex  |60000.000000 (60000)|0.000000 (0)      |0.000000 (0)        |0.000000 (0)      |
|Trigger        |51707.000000 (51707)|0.000000 (0)      |0.000000 (0)        |0.000000 (0)      |
|SFOS           |0.000000 (0)        |3532.666260 (3740)|10402.055664 (11182)|7845.701660 (8594)|
|NotOverlaps    |0.000000 (0)        |3532.666260 (3740)|10385.311523 (11154)|7845.701660 (8594)|
|Kinematic      |0.000000 (0)        |3485.004639 (3691)|10124.589844 (10878)|7517.273438 (8227)|
|TriggerMatched |0.000000 (0)        |3453.334717 (3659)|10067.655273 (10818)|7482.468750 (8189)|
|MuType         |0.000000 (0)        |3459.312988 (3665)|10067.552734 (10818)|7476.794434 (8178)|
|DeltaR         |0.000000 (0)        |3448.200439 (3654)|10046.569336 (10796)|7465.588867 (8166)|
|Isolation      |0.000000 (0)        |2832.440674 (3004)|8286.253906 (8909)  |6335.695312 (6934)|
|ElectronID     |0.000000 (0)        |2832.440674 (3004)|8286.253906 (8909)  |6335.695312 (6934)|
|ImpactParameter|0.000000 (0)        |2822.229248 (2993)|8155.364258 (8767)  |6168.345215 (6751)|
|Jpsi           |0.000000 (0)        |2822.229248 (2993)|8154.421875 (8766)  |6167.449219 (6750)|
|Upsilon        |0.000000 (0)        |2818.388428 (2989)|8153.511230 (8765)  |6146.797363 (6726)|
|LowMassVeto    |0.000000 (0)        |2818.388428 (2989)|8151.680664 (8763)  |6145.841797 (6725)|
|HWindow        |0.000000 (0)        |2452.964600 (2604)|7471.768066 (8034)  |5904.102051 (6457)|
|ZVeto          |0.000000 (0)        |1723.262085 (1830)|7471.768066 (8034)  |3992.804932 (4368)|
|LooseSR        |0.000000 (0)        |1723.262085 (1830)|7471.768066 (8034)  |3992.804932 (4368)|
|MediumSR       |0.000000 (0)        |1652.686035 (1756)|7320.286133 (7873)  |3964.583740 (4337)|
-------------------------------------------------------------------------------------------------'''

# Result of ZdZdPP cutflow using the new Medium SR cut
# Also the order of DeltaR and MuType are switched and the ImpactParameterZ cut is added to check if it has an affect (should be already applied in the new baseline cuts)
zdzdPP_newNtuple_newMSR_str = '''|                |#==561511           |#==5615111        |#==5615112          |#==5615113        |
--------------------------------------------------------------------------------------------------
|All             |60000.000000 (60000)|0.000000 (0)      |0.000000 (0)        |0.000000 (0)      |
|Cleaning        |60000.000000 (60000)|0.000000 (0)      |0.000000 (0)        |0.000000 (0)      |
|PrimaryVertex   |60000.000000 (60000)|0.000000 (0)      |0.000000 (0)        |0.000000 (0)      |
|Trigger         |51707.000000 (51707)|0.000000 (0)      |0.000000 (0)        |0.000000 (0)      |
|SFOS            |0.000000 (0)        |3532.666260 (3740)|10402.055664 (11182)|7845.701660 (8594)|
|NotOverlaps     |0.000000 (0)        |3532.666260 (3740)|10385.311523 (11154)|7845.701660 (8594)|
|Kinematic       |0.000000 (0)        |3485.004639 (3691)|10124.589844 (10878)|7517.273438 (8227)|
|TriggerMatched  |0.000000 (0)        |3453.334717 (3659)|10067.655273 (10818)|7482.468750 (8189)|
|DeltaR          |0.000000 (0)        |3448.200439 (3654)|10047.579102 (10797)|7488.142578 (8200)|
|MuType          |0.000000 (0)        |3448.200439 (3654)|10046.569336 (10796)|7465.588867 (8166)|
|Isolation       |0.000000 (0)        |2832.440674 (3004)|8286.253906 (8909)  |6335.695312 (6934)|
|ElectronID      |0.000000 (0)        |2832.440674 (3004)|8286.253906 (8909)  |6335.695312 (6934)|
|ImpactParameter |0.000000 (0)        |2822.229248 (2993)|8155.364258 (8767)  |6168.345215 (6751)|
|ImpactParameterZ|0.000000 (0)        |2822.229248 (2993)|8155.364258 (8767)  |6168.345215 (6751)|
|Jpsi            |0.000000 (0)        |2822.229248 (2993)|8154.421875 (8766)  |6167.449219 (6750)|
|Upsilon         |0.000000 (0)        |2818.388428 (2989)|8153.511230 (8765)  |6146.797363 (6726)|
|LowMassVeto     |0.000000 (0)        |2818.388428 (2989)|8151.680664 (8763)  |6145.841797 (6725)|
|HWindow         |0.000000 (0)        |2452.964600 (2604)|7471.768066 (8034)  |5904.102051 (6457)|
|ZVeto           |0.000000 (0)        |1723.262085 (1830)|7471.768066 (8034)  |3992.804932 (4368)|
|LooseSR         |0.000000 (0)        |1723.262085 (1830)|7471.768066 (8034)  |3992.804932 (4368)|
|MediumSR        |0.000000 (0)        |1652.686035 (1756)|7320.286133 (7873)  |3964.583740 (4337)|
--------------------------------------------------------------------------------------------------'''

# Same as above but without the ImpactParameterZ cut
zddPP_newNtuple_newMSR_noz0_str = '''|               |#==561511           |#==5615111        |#==5615112          |#==5615113        |
-------------------------------------------------------------------------------------------------
|All            |60000.000000 (60000)|0.000000 (0)      |0.000000 (0)        |0.000000 (0)      |
|Cleaning       |60000.000000 (60000)|0.000000 (0)      |0.000000 (0)        |0.000000 (0)      |
|PrimaryVertex  |60000.000000 (60000)|0.000000 (0)      |0.000000 (0)        |0.000000 (0)      |
|Trigger        |51707.000000 (51707)|0.000000 (0)      |0.000000 (0)        |0.000000 (0)      |
|SFOS           |0.000000 (0)        |3532.666260 (3740)|10402.055664 (11182)|7845.701660 (8594)|
|NotOverlaps    |0.000000 (0)        |3532.666260 (3740)|10385.311523 (11154)|7845.701660 (8594)|
|Kinematic      |0.000000 (0)        |3485.004639 (3691)|10124.589844 (10878)|7517.273438 (8227)|
|TriggerMatched |0.000000 (0)        |3453.334717 (3659)|10067.655273 (10818)|7482.468750 (8189)|
|DeltaR         |0.000000 (0)        |3448.200439 (3654)|10047.579102 (10797)|7488.142578 (8200)|
|MuType         |0.000000 (0)        |3448.200439 (3654)|10046.569336 (10796)|7465.588867 (8166)|
|Isolation      |0.000000 (0)        |2832.440674 (3004)|8286.253906 (8909)  |6335.695312 (6934)|
|ElectronID     |0.000000 (0)        |2832.440674 (3004)|8286.253906 (8909)  |6335.695312 (6934)|
|ImpactParameter|0.000000 (0)        |2822.229248 (2993)|8155.364258 (8767)  |6168.345215 (6751)|
|Jpsi           |0.000000 (0)        |2822.229248 (2993)|8154.421875 (8766)  |6167.449219 (6750)|
|Upsilon        |0.000000 (0)        |2818.388428 (2989)|8153.511230 (8765)  |6146.797363 (6726)|
|LowMassVeto    |0.000000 (0)        |2818.388428 (2989)|8151.680664 (8763)  |6145.841797 (6725)|
|HWindow        |0.000000 (0)        |2452.964600 (2604)|7471.768066 (8034)  |5904.102051 (6457)|
|ZVeto          |0.000000 (0)        |1723.262085 (1830)|7471.768066 (8034)  |3992.804932 (4368)|
|LooseSR        |0.000000 (0)        |1723.262085 (1830)|7471.768066 (8034)  |3992.804932 (4368)|
|MediumSR       |0.000000 (0)        |1652.686035 (1756)|7320.286133 (7873)  |3964.583740 (4337)|
-------------------------------------------------------------------------------------------------'''

In [ ]:
scott_newNtuple_df = cf.simplify_Scott_cutflow(cf.str_to_df_Scott(scott_newNtuple_str))
display(scott_newNtuple_df)

,Cut,weights_4e,events_4e,weights_2e2m,events_2e2m,weights_4m,events_4m,weights_All,events_All
0,weight,,,,,,,60000,60000
1,clean,,,,,,,60000,60000
2,pv,,,,,,,60000,60000
3,trigger,,,,,,,51714,51707
4,quad sfos,,,,,,,23565,23516
5,quad or,,,,,,,23538,23488
6,quad kin,,,,,,,22840,22796
7,quad trigmatch,,,,,,,22708,22666
8,quad dr,,,,,,,22676,22634
9,quad mqual,,,,,,,22659,22616
10,isol,2841.4,3004,8315.0,8909,6350.3,6934,17507,18847
11,e_id,2841.4,3004,8315.0,8909,6350.3,6934,17507,18847
12,impact,2831.0,2993,8184.5,8767,6180.3,6751,17196,18511
13,jpsi,2831.0,2993,8183.5,8766,6179.5,6750,17194,18509
14,upsilon,2827.9,2989,8182.4,8765,6157.3,6726,17168,18480
15,lowmveto,2827.9,2989,8180.9,8763,6156.4,6725,17165,18477
16,hwind,2461.5,2604,7494.4,8034,5909.5,6457,15865,17095
17,zveto,1717.3,1819,7494.4,8034,3997.3,4359,13209,14212
18,loose,1710.8,1812,7486.1,8025,3967.1,4326,13164,14163
19,medium,1703.2,1804,7458.7,7994,3963.1,4321,13125,14119

In [28]:
zdzdPP_newNtuple_oldMSR_df = cf.simplify_ZdZdPP_cutflow(cf.str_to_df_ZdZdPP(zdzdPP_newNtuple_oldMSR_str))
display(zdzdPP_newNtuple_oldMSR_df)

,Cuts,weights_4e,events_4e,weights_2e2m,events_2e2m,weights_4m,events_4m,weights_All,events_All
0,All,0.000000,0,0.000000,0,0.000000,0,60000.000000,60000
1,Cleaning,0.000000,0,0.000000,0,0.000000,0,60000.000000,60000
2,PrimaryVertex,0.000000,0,0.000000,0,0.000000,0,60000.000000,60000
3,Trigger,0.000000,0,0.000000,0,0.000000,0,51707.000000,51707
4,SFOS,3532.666260,3740,10402.055664,11182,7845.701660,8594,21780.423584,23516
5,NotOverlaps,3532.666260,3740,10385.311523,11154,7845.701660,8594,21763.679443,23488
6,Kinematic,3485.004639,3691,10124.589844,10878,7517.273438,8227,21126.867921,22796
7,TriggerMatched,3453.334717,3659,10067.655273,10818,7482.468750,8189,21003.458740,22666
8,MuType,3459.312988,3665,10067.552734,10818,7476.794434,8178,21003.660156,22661
9,DeltaR,3448.200439,3654,10046.569336,10796,7465.588867,8166,20960.358642,22616
10,Isolation,2832.440674,3004,8286.253906,8909,6335.695312,6934,17454.389892,18847
11,ElectronID,2832.440674,3004,8286.253906,8909,6335.695312,6934,17454.389892,18847
12,ImpactParameter,2822.229248,2993,8155.364258,8767,6168.345215,6751,17145.938721,18511
13,Jpsi,2822.229248,2993,8154.421875,8766,6167.449219,6750,17144.100342,18509
14,Upsilon,2818.388428,2989,8153.511230,8765,6146.797363,6726,17118.697021,18480
15,LowMassVeto,2818.388428,2989,8151.680664,8763,6145.841797,6725,17115.910889,18477
16,HWindow,2452.964600,2604,7471.768066,8034,5904.102051,6457,15828.834717,17095
17,ZVeto,1723.262085,1830,7471.768066,8034,3992.804932,4368,13187.835083,14232
18,LooseSR,1723.262085,1830,7471.768066,8034,3992.804932,4368,13187.835083,14232
19,MediumSR,1652.686035,1756,7320.286133,7873,3964.583740,4337,12937.555908,13966

In [29]:
zdzdPP_newNtuple_newMSR_df = cf.simplify_ZdZdPP_cutflow(cf.str_to_df_ZdZdPP(zdzdPP_newNtuple_newMSR_str))
display(zdzdPP_newNtuple_newMSR_df)

,Cuts,weights_4e,events_4e,weights_2e2m,events_2e2m,weights_4m,events_4m,weights_All,events_All
0,All,0.000000,0,0.000000,0,0.000000,0,60000.000000,60000
1,Cleaning,0.000000,0,0.000000,0,0.000000,0,60000.000000,60000
2,PrimaryVertex,0.000000,0,0.000000,0,0.000000,0,60000.000000,60000
3,Trigger,0.000000,0,0.000000,0,0.000000,0,51707.000000,51707
4,SFOS,3532.666260,3740,10402.055664,11182,7845.701660,8594,21780.423584,23516
5,NotOverlaps,3532.666260,3740,10385.311523,11154,7845.701660,8594,21763.679443,23488
6,Kinematic,3485.004639,3691,10124.589844,10878,7517.273438,8227,21126.867921,22796
7,TriggerMatched,3453.334717,3659,10067.655273,10818,7482.468750,8189,21003.458740,22666
8,DeltaR,3448.200439,3654,10047.579102,10797,7488.142578,8200,20983.922119,22651
9,MuType,3448.200439,3654,10046.569336,10796,7465.588867,8166,20960.358642,22616
10,Isolation,2832.440674,3004,8286.253906,8909,6335.695312,6934,17454.389892,18847
11,ElectronID,2832.440674,3004,8286.253906,8909,6335.695312,6934,17454.389892,18847
12,ImpactParameter,2822.229248,2993,8155.364258,8767,6168.345215,6751,17145.938721,18511
13,ImpactParameterZ,2822.229248,2993,8155.364258,8767,6168.345215,6751,17145.938721,18511
14,Jpsi,2822.229248,2993,8154.421875,8766,6167.449219,6750,17144.100342,18509
15,Upsilon,2818.388428,2989,8153.511230,8765,6146.797363,6726,17118.697021,18480
16,LowMassVeto,2818.388428,2989,8151.680664,8763,6145.841797,6725,17115.910889,18477
17,HWindow,2452.964600,2604,7471.768066,8034,5904.102051,6457,15828.834717,17095
18,ZVeto,1723.262085,1830,7471.768066,8034,3992.804932,4368,13187.835083,14232
19,LooseSR,1723.262085,1830,7471.768066,8034,3992.804932,4368,13187.835083,14232
20,MediumSR,1652.686035,1756,7320.286133,7873,3964.583740,4337,12937.555908,13966

In [44]:
zddPP_newNtuple_newMSR_noz0_df = cf.simplify_ZdZdPP_cutflow(cf.str_to_df_ZdZdPP(zddPP_newNtuple_newMSR_noz0_str))
display(zddPP_newNtuple_newMSR_noz0_df)

,Cuts,weights_4e,events_4e,weights_2e2m,events_2e2m,weights_4m,events_4m,weights_All,events_All
0,All,0.000000,0,0.000000,0,0.000000,0,60000.000000,60000
1,Cleaning,0.000000,0,0.000000,0,0.000000,0,60000.000000,60000
2,PrimaryVertex,0.000000,0,0.000000,0,0.000000,0,60000.000000,60000
3,Trigger,0.000000,0,0.000000,0,0.000000,0,51707.000000,51707
4,SFOS,3532.666260,3740,10402.055664,11182,7845.701660,8594,21780.423584,23516
5,NotOverlaps,3532.666260,3740,10385.311523,11154,7845.701660,8594,21763.679443,23488
6,Kinematic,3485.004639,3691,10124.589844,10878,7517.273438,8227,21126.867921,22796
7,TriggerMatched,3453.334717,3659,10067.655273,10818,7482.468750,8189,21003.458740,22666
8,DeltaR,3448.200439,3654,10047.579102,10797,7488.142578,8200,20983.922119,22651
9,MuType,3448.200439,3654,10046.569336,10796,7465.588867,8166,20960.358642,22616
10,Isolation,2832.440674,3004,8286.253906,8909,6335.695312,6934,17454.389892,18847
11,ElectronID,2832.440674,3004,8286.253906,8909,6335.695312,6934,17454.389892,18847
12,ImpactParameter,2822.229248,2993,8155.364258,8767,6168.345215,6751,17145.938721,18511
13,Jpsi,2822.229248,2993,8154.421875,8766,6167.449219,6750,17144.100342,18509
14,Upsilon,2818.388428,2989,8153.511230,8765,6146.797363,6726,17118.697021,18480
15,LowMassVeto,2818.388428,2989,8151.680664,8763,6145.841797,6725,17115.910889,18477
16,HWindow,2452.964600,2604,7471.768066,8034,5904.102051,6457,15828.834717,17095
17,ZVeto,1723.262085,1830,7471.768066,8034,3992.804932,4368,13187.835083,14232
18,LooseSR,1723.262085,1830,7471.768066,8034,3992.804932,4368,13187.835083,14232
19,MediumSR,1652.686035,1756,7320.286133,7873,3964.583740,4337,12937.555908,13966

In [17]:
cut_names = ['All',
 'PS: Cleaning',
 'PS: Primary Vertex',
 'PS: Trigger',
 'QS: SFOS',
 'QS: Overlaps',
 'QS: Kinematic',
 'QS: Trigger Matched',
 'QS: DeltaR',
 'QS: Muon Quality',
 'ES: Isolation',
 'ES: Electron ID',
 'ES: Impact Parameter',
#  'ES: Impact ParameterZ',
 'ES: Jpsi',
 'ES: Upsilon',
 'ES: Low Mass Veto',
 'ES: Higgs Window',
 'ES: Z-Veto',
 'ES: Loose SR',
 'ES: Medium SR']

# Add a 'Cut name' column to each dataframe with the cut names
scott_newNtuple_df['Cut name'] = cut_names
zdzdPP_newNtuple_oldMSR_df['Cut name'] = cut_names

NameError: name 'scott_newNtuple_df' is not defined

In [39]:
cut_names2 = ['All',
 'PS: Cleaning',
 'PS: Primary Vertex',
 'PS: Trigger',
 'QS: SFOS',
 'QS: Overlaps',
 'QS: Kinematic',
 'QS: Trigger Matched',
 'QS: DeltaR',
 'QS: Muon Quality',
 'ES: Isolation',
 'ES: Electron ID',
 'ES: Impact Parameter',
 'ES: Impact ParameterZ',
 'ES: Jpsi',
 'ES: Upsilon',
 'ES: Low Mass Veto',
 'ES: Higgs Window',
 'ES: Z-Veto',
 'ES: Loose SR',
 'ES: Medium SR']
zdzdPP_newNtuple_newMSR_df['Cut name'] = cut_names2

In [47]:
# Create a DF from with these columns: 'Cut names', with the values from cut_names, 'events_4e_ZdZdPP' with the values from zddPP_newNtuple_newMSR_noz0_df['events_4e'] and 'events_4e_scott' with the values from  scott_newNtuple_df['events_4e']
evt_comparison_df = pd.DataFrame({
    'Cut name': cut_names,
    'events_4e_ZdZdPP': zddPP_newNtuple_newMSR_noz0_df['events_4e'],
    'events_4e_scott': scott_newNtuple_df['events_4e'],
    'events_2e2m_ZdZdPP': zddPP_newNtuple_newMSR_noz0_df['events_2e2m'],
    'events_2e2m_scott': scott_newNtuple_df['events_2e2m'],
    'events_4m_ZdZdPP': zddPP_newNtuple_newMSR_noz0_df['events_4m'],
    'events_4m_scott': scott_newNtuple_df['events_4m'],
    'events_All_ZdZdPP': zddPP_newNtuple_newMSR_noz0_df['events_All'],
    'events_All_scott': scott_newNtuple_df['events_All']
})
display(evt_comparison_df)

,Cut name,events_4e_ZdZdPP,events_4e_scott,events_2e2m_ZdZdPP,events_2e2m_scott,events_4m_ZdZdPP,events_4m_scott,events_All_ZdZdPP,events_All_scott
0,All,0,,0,,0,,60000,60000
1,PS: Cleaning,0,,0,,0,,60000,60000
2,PS: Primary Vertex,0,,0,,0,,60000,60000
3,PS: Trigger,0,,0,,0,,51707,51707
4,QS: SFOS,3740,,11182,,8594,,23516,23516
5,QS: Overlaps,3740,,11154,,8594,,23488,23488
6,QS: Kinematic,3691,,10878,,8227,,22796,22796
7,QS: Trigger Matched,3659,,10818,,8189,,22666,22666
8,QS: DeltaR,3654,,10797,,8200,,22651,22634
9,QS: Muon Quality,3654,,10796,,8166,,22616,22616
10,ES: Isolation,3004,3004,8909,8909,6934,6934,18847,18847
11,ES: Electron ID,3004,3004,8909,8909,6934,6934,18847,18847
12,ES: Impact Parameter,2993,2993,8767,8767,6751,6751,18511,18511
13,ES: Jpsi,2993,2993,8766,8766,6750,6750,18509,18509
14,ES: Upsilon,2989,2989,8765,8765,6726,6726,18480,18480
15,ES: Low Mass Veto,2989,2989,8763,8763,6725,6725,18477,18477
16,ES: Higgs Window,2604,2604,8034,8034,6457,6457,17095,17095
17,ES: Z-Veto,1830,1819,8034,8034,4368,4359,14232,14212
18,ES: Loose SR,1830,1812,8034,8025,4368,4326,14232,14163
19,ES: Medium SR,1756,1804,7873,7994,4337,4321,13966,14119

In [53]:
# Create a DF from with these columns: 'Cut names', with the values from cut_names, 'weights_4e_ZdZdPP' with the values from zddPP_newNtuple_newMSR_noz0_df['weights_4e'] and 'weights_4e_scott' with the values from  scott_newNtuple_df['weights_4e']
weight_comparison_df = pd.DataFrame({
    'Cut name': cut_names,
    'weights_4e_ZdZdPP': zddPP_newNtuple_newMSR_noz0_df['weights_4e'],
    'weights_4e_scott': scott_newNtuple_df['weights_4e'],
    'weights_2e2m_ZdZdPP': zddPP_newNtuple_newMSR_noz0_df['weights_2e2m'],
    'weights_2e2m_scott': scott_newNtuple_df['weights_2e2m'],
    'weights_4m_ZdZdPP': zddPP_newNtuple_newMSR_noz0_df['weights_4m'],
    'weights_4m_scott': scott_newNtuple_df['weights_4m'],
    'weights_All_ZdZdPP': zddPP_newNtuple_newMSR_noz0_df['weights_All'],
    'weights_All_scott': scott_newNtuple_df['weights_All']
})
# Add a column which is the ratio of 'weights_All_ZdZdPP' to 'weights_All_scott' (the latter must be converted to float)
weight_comparison_df['weights_All_ratio'] = weight_comparison_df['weights_All_ZdZdPP'] / weight_comparison_df['weights_All_scott'].astype(float)

display(weight_comparison_df)
weight_comparison_df.info()

,Cut name,weights_4e_ZdZdPP,weights_4e_scott,weights_2e2m_ZdZdPP,weights_2e2m_scott,weights_4m_ZdZdPP,weights_4m_scott,weights_All_ZdZdPP,weights_All_scott,weights_All_ratio
0,All,0.000000,,0.000000,,0.000000,,60000.000000,60000,1.000000
1,PS: Cleaning,0.000000,,0.000000,,0.000000,,60000.000000,60000,1.000000
2,PS: Primary Vertex,0.000000,,0.000000,,0.000000,,60000.000000,60000,1.000000
3,PS: Trigger,0.000000,,0.000000,,0.000000,,51707.000000,51714,0.999865
4,QS: SFOS,3532.666260,,10402.055664,,7845.701660,,21780.423584,23565,0.924270
5,QS: Overlaps,3532.666260,,10385.311523,,7845.701660,,21763.679443,23538,0.924619
6,QS: Kinematic,3485.004639,,10124.589844,,7517.273438,,21126.867921,22840,0.924994
7,QS: Trigger Matched,3453.334717,,10067.655273,,7482.468750,,21003.458740,22708,0.924937
8,QS: DeltaR,3448.200439,,10047.579102,,7488.142578,,20983.922119,22676,0.925380
9,QS: Muon Quality,3448.200439,,10046.569336,,7465.588867,,20960.358642,22659,0.925035
10,ES: Isolation,2832.440674,2841.4,8286.253906,8315.0,6335.695312,6350.3,17454.389892,17507,0.996995
11,ES: Electron ID,2832.440674,2841.4,8286.253906,8315.0,6335.695312,6350.3,17454.389892,17507,0.996995
12,ES: Impact Parameter,2822.229248,2831.0,8155.364258,8184.5,6168.345215,6180.3,17145.938721,17196,0.997089
13,ES: Jpsi,2822.229248,2831.0,8154.421875,8183.5,6167.449219,6179.5,17144.100342,17194,0.997098
14,ES: Upsilon,2818.388428,2827.9,8153.511230,8182.4,6146.797363,6157.3,17118.697021,17168,0.997128
15,ES: Low Mass Veto,2818.388428,2827.9,8151.680664,8180.9,6145.841797,6156.4,17115.910889,17165,0.997140
16,ES: Higgs Window,2452.964600,2461.5,7471.768066,7494.4,5904.102051,5909.5,15828.834717,15865,0.997720
17,ES: Z-Veto,1723.262085,1717.3,7471.768066,7494.4,3992.804932,3997.3,13187.835083,13209,0.998398
18,ES: Loose SR,1723.262085,1710.8,7471.768066,7486.1,3992.804932,3967.1,13187.835083,13164,1.001811
19,ES: Medium SR,1652.686035,1703.2,7320.286133,7458.7,3964.583740,3963.1,12937.555908,13125,0.985719

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Cut name             20 non-null     object
 1   weights_4e_ZdZdPP    20 non-null     float64
 2   weights_4e_scott     20 non-null     object
 3   weights_2e2m_ZdZdPP  20 non-null     float64
 4   weights_2e2m_scott   20 non-null     object
 5   weights_4m_ZdZdPP    20 non-null     float64
 6   weights_4m_scott     20 non-null     object
 7   weights_All_ZdZdPP   20 non-null     float64
 8   weights_All_scott    20 non-null     object
 9   weights_All_ratio    20 non-null     float64
dtypes: float64(5), object(5)
memory usage: 1.7+ KB

In [49]:
# Save the comparison DFs to an Excel file with two sheets, one for the event comparison and one for the weight comparison
with pd.ExcelWriter(cutflow_dir + 'cutflow_comparison.xlsx') as writer:
    evt_comparison_df.to_excel(writer, sheet_name='Event Comparison', index=False)
    weight_comparison_df.to_excel(writer, sheet_name='Weight Comparison', index=False)

In [41]:
# Save the last 3 DFs to a spreadsheet
cf.make_spreadsheet(cutflow_dir + '2026-02-24_newNtuple-cutflows.xlsx', {'scott_newNtuple': scott_newNtuple_df,
                                                                              'zdzdPP_newNtuple_oldMSR': zdzdPP_newNtuple_oldMSR_df,
                                                                              'zdzdPP_newNtuple_newMSR': zdzdPP_newNtuple_newMSR_df})

***
## 2026-03-23
***
Scott sent a latest version of his cutflow where he adjusted some of the cuts (e.g. the z-veto cutoff was changed from minimum 20 GeV to minimum 10 GeV ).

In [ ]:
cut_names_20260323 = ['All',
 'PS: Cleaning',
 'PS: Primary Vertex',
 'PS: Trigger',
 'QS: SFOS',
 'QS: Overlaps',
 'QS: Kinematic',
 'QS: Trigger Matched',
 'QS: DeltaR',
 'QS: Muon Quality',
 'ES: Isolation',
 'ES: Electron ID',
 'ES: Impact Parameter',
 'ES: Jpsi',
 'ES: Upsilon',
 'ES: Low Mass Veto',
 'ES: Higgs Window',
 'ES: Z-Veto',
 'ES: Loose SR',
 'ES: Medium SR']
len(cut_names_20260323)

Scott's new cutflow

In [21]:
scott_mc23a_mZd30_20260320_dict = cf.parse_Scott_cutflow_file(cutflow_dir + '2026-03-20_Scott-cutflow_mZd30.txt')
scott_mc23a_mZd30_20260320_df = cf.simplify_Scott_cutflow(cf.str_to_df_Scott(scott_mc23a_mZd30_20260320_dict['zd30_23a --- reco']))
scott_mc23a_mZd30_20260320_df['Cut name'] = cut_names_20260323
cf.make_spreadsheet(cutflow_dir + '2026-03-20_Scott-cutflow_mZd30.xlsx', {'mc23a_mZd30': scott_mc23a_mZd30_20260320_df})

scott_mc23a_mZd30_20260320_df

,Cut,weights_4e,events_4e,weights_2e2m,events_2e2m,weights_4m,events_4m,weights_All,events_All,Cut name
0,weight,,,,,,,60000,60000,All
1,clean,,,,,,,60000,60000,PS: Cleaning
2,pv,,,,,,,60000,60000,PS: Primary Vertex
3,trigger,,,,,,,51714,51707,PS: Trigger
4,quad sfos,,,,,,,23565,23516,QS: SFOS
5,quad or,,,,,,,23538,23488,QS: Overlaps
6,quad kin,,,,,,,22840,22796,QS: Kinematic
7,quad trigmatch,,,,,,,22708,22666,QS: Trigger Matched
8,quad dr,,,,,,,22676,22634,QS: DeltaR
9,quad mqual,,,,,,,22659,22616,QS: Muon Quality
10,isol,2841.4,3004,8315.0,8909,6350.3,6934,17507,18847,ES: Isolation
11,e_id,2841.4,3004,8315.0,8909,6350.3,6934,17507,18847,ES: Electron ID
12,impact,2831.0,2993,8184.5,8767,6180.3,6751,17196,18511,ES: Impact Parameter
13,jpsi,2831.0,2993,8183.5,8766,6179.5,6750,17194,18509,ES: Jpsi
14,upsilon,2827.9,2989,8182.4,8765,6157.3,6726,17168,18480,ES: Upsilon
15,lowmveto,2827.9,2989,8180.9,8763,6156.4,6725,17165,18477,ES: Low Mass Veto
16,hwind,2461.5,2604,7494.4,8034,5909.5,6457,15865,17095,ES: Higgs Window
17,zveto,1717.3,1819,7494.4,8034,3997.3,4359,13209,14212,ES: Z-Veto
18,loose,1717.3,1819,7494.4,8034,3997.3,4359,13209,14212,ES: Loose SR
19,medium,1708.8,1810,7458.7,7994,3992.4,4353,13160,14157,ES: Medium SR

ZdZdPP new cutflow

In [8]:
ZdZdPP_mc23a_mZd30_20260323_str = '''|               |#==561511           |#==5615111        |#==5615112          |#==5615113        |
-------------------------------------------------------------------------------------------------
|All            |60000.000000 (60000)|0.000000 (0)      |0.000000 (0)        |0.000000 (0)      |
|Cleaning       |60000.000000 (60000)|0.000000 (0)      |0.000000 (0)        |0.000000 (0)      |
|PrimaryVertex  |60000.000000 (60000)|0.000000 (0)      |0.000000 (0)        |0.000000 (0)      |
|Trigger        |51707.000000 (51707)|0.000000 (0)      |0.000000 (0)        |0.000000 (0)      |
|SFOS           |0.000000 (0)        |3532.666260 (3740)|10402.055664 (11182)|7845.701660 (8594)|
|NotOverlaps    |0.000000 (0)        |3532.666260 (3740)|10385.311523 (11154)|7845.701660 (8594)|
|Kinematic      |0.000000 (0)        |3485.004639 (3691)|10124.589844 (10878)|7517.273438 (8227)|
|TriggerMatched |0.000000 (0)        |3453.334717 (3659)|10067.655273 (10818)|7482.468750 (8189)|
|DeltaR         |0.000000 (0)        |3448.200439 (3654)|10047.579102 (10797)|7488.142578 (8200)|
|MuType         |0.000000 (0)        |3448.200439 (3654)|10046.569336 (10796)|7465.588867 (8166)|
|Isolation      |0.000000 (0)        |2832.440674 (3004)|8286.253906 (8909)  |6335.695312 (6934)|
|ElectronID     |0.000000 (0)        |2832.440674 (3004)|8286.253906 (8909)  |6335.695312 (6934)|
|ImpactParameter|0.000000 (0)        |2822.229248 (2993)|8155.364258 (8767)  |6168.345215 (6751)|
|Jpsi           |0.000000 (0)        |2822.229248 (2993)|8154.421875 (8766)  |6167.449219 (6750)|
|Upsilon        |0.000000 (0)        |2818.388428 (2989)|8153.511230 (8765)  |6146.797363 (6726)|
|LowMassVeto    |0.000000 (0)        |2818.388428 (2989)|8151.680664 (8763)  |6145.841797 (6725)|
|HWindow        |0.000000 (0)        |2452.964600 (2604)|7471.768066 (8034)  |5904.102051 (6457)|
|ZVeto          |0.000000 (0)        |1723.262085 (1830)|7471.768066 (8034)  |3992.804932 (4368)|
|LooseSR        |0.000000 (0)        |1723.262085 (1830)|7471.768066 (8034)  |3992.804932 (4368)|
|MediumSR       |0.000000 (0)        |1652.686035 (1756)|7320.286133 (7873)  |3964.583740 (4337)|
-------------------------------------------------------------------------------------------------'''

## 2026-03-30 - Getting 10 data22 samples
Below is the output of the command:

```rucio list-files data22_13p6TeV.00430536.physics_Main.deriv.DAOD_PHYS.r15869_p6304_p7019```

Which lists the output of a subset of 2022 ATLAS data samples.

In [11]:
data22_str = '''+-------------------------------------------------------+--------------------------------------+-------------+------------+----------+
| SCOPE:NAME                                            | GUID                                 | ADLER32     | FILESIZE   | EVENTS   |
|-------------------------------------------------------+--------------------------------------+-------------+------------+----------|
| data22_13p6TeV:DAOD_PHYS.46780328._000001.pool.root.1 | 5CAB674A-6268-244C-AE6E-01C6D915E7D5 | ad:f9f6a243 | 973.315 MB | 71879    |
| data22_13p6TeV:DAOD_PHYS.46780328._000002.pool.root.1 | 08190D6E-275C-1F40-98A0-AD3C31CBAB9F | ad:71a66fac | 1.004 GB   | 62739    |
| data22_13p6TeV:DAOD_PHYS.46780328._000003.pool.root.1 | 08B61F55-D53A-8F48-A848-4AB1CF249032 | ad:5a8ad110 | 948.669 MB | 59403    |
| data22_13p6TeV:DAOD_PHYS.46780328._000004.pool.root.1 | AC5263F1-CEC2-3841-B4F4-522A9848DB67 | ad:918af8f2 | 865.862 MB | 53616    |
| data22_13p6TeV:DAOD_PHYS.46780328._000005.pool.root.1 | 4E266B62-DE58-A846-A7A1-E5D39522DF3F | ad:76cbd024 | 780.557 MB | 50148    |
| data22_13p6TeV:DAOD_PHYS.46780328._000006.pool.root.1 | 634F9242-6827-934D-9EA5-198A1EDF03B1 | ad:3f488de7 | 807.581 MB | 51261    |
| data22_13p6TeV:DAOD_PHYS.46780328._000007.pool.root.1 | C192A6EA-A084-B641-AD3C-B1B751DD8863 | ad:52605e6e | 834.185 MB | 49976    |
| data22_13p6TeV:DAOD_PHYS.46780328._000008.pool.root.1 | EC0BBA5D-0AEF-054B-A33C-EB6AA8B84262 | ad:ded30f79 | 851.182 MB | 50887    |
| data22_13p6TeV:DAOD_PHYS.46780328._000011.pool.root.1 | AF492A86-197E-BA44-AC34-D8A7EBC09D63 | ad:ecc0c7bc | 1.624 GB   | 99430    |
| data22_13p6TeV:DAOD_PHYS.46780328._000012.pool.root.1 | E2FF7196-A4B6-3244-8AA9-96A9C0A5296F | ad:0bab98fd | 2.436 GB   | 152385   |
| data22_13p6TeV:DAOD_PHYS.46780328._000013.pool.root.1 | E7ADB622-E776-7546-9319-896424C41065 | ad:bebf68b6 | 1.749 GB   | 108395   |
| data22_13p6TeV:DAOD_PHYS.46780328._000014.pool.root.1 | 6FDD2FCC-3E9B-4F4E-83D5-BDA8A25336A7 | ad:94e9d29c | 2.310 GB   | 148961   |
| data22_13p6TeV:DAOD_PHYS.46780328._000015.pool.root.1 | 4A4F7BB0-AB2B-F346-BB45-86A252E13B79 | ad:8f3ccceb | 2.542 GB   | 153816   |
| data22_13p6TeV:DAOD_PHYS.46780328._000016.pool.root.1 | F6BD656F-1820-0C48-9B4A-B5FB0C0C9FEA | ad:8c612c1c | 2.438 GB   | 154076   |
| data22_13p6TeV:DAOD_PHYS.46780328._000017.pool.root.1 | 5DDB1CE9-3719-6042-8770-FD9E1FF688D9 | ad:e005e0eb | 2.360 GB   | 153621   |
| data22_13p6TeV:DAOD_PHYS.46780328._000018.pool.root.1 | 06DDF986-3756-F345-9278-D100D80E0169 | ad:0b20f40d | 2.500 GB   | 147260   |
| data22_13p6TeV:DAOD_PHYS.46780328._000019.pool.root.1 | 2D34EAD9-755B-D442-B915-37F2644F2E3E | ad:20ece2d6 | 2.424 GB   | 128777   |
| data22_13p6TeV:DAOD_PHYS.46780328._000020.pool.root.1 | A88F22BC-9A38-3242-8A65-BE9A4047843E | ad:9bb1db34 | 3.063 GB   | 159936   |
| data22_13p6TeV:DAOD_PHYS.46780328._000021.pool.root.1 | 3E26552F-66AF-2440-AFAB-7BB7D7B0EC69 | ad:47d0cc4e | 2.776 GB   | 137941   |
| data22_13p6TeV:DAOD_PHYS.46780328._000022.pool.root.1 | B0252B95-5D1F-0B41-B9A8-AAC666F8ECAE | ad:55a5b803 | 2.794 GB   | 139102   |
| data22_13p6TeV:DAOD_PHYS.46780328._000023.pool.root.1 | DE1CD8FB-24B5-F840-9901-FF4D1E1A0D70 | ad:7c1c9524 | 2.873 GB   | 143634   |
| data22_13p6TeV:DAOD_PHYS.46780328._000024.pool.root.1 | 7EF6F2FF-7B59-6147-A862-E5B4E588EA99 | ad:b927afee | 2.727 GB   | 136008   |
| data22_13p6TeV:DAOD_PHYS.46780328._000025.pool.root.1 | 381AFD9F-FDC5-DF4B-BF6A-9651E38E60E0 | ad:dc2890f5 | 2.712 GB   | 134832   |
| data22_13p6TeV:DAOD_PHYS.46780328._000026.pool.root.1 | D863FD1E-6C1A-634E-B9ED-15E2BCCDF9D9 | ad:000884de | 2.729 GB   | 135300   |
| data22_13p6TeV:DAOD_PHYS.46780328._000027.pool.root.1 | 28DB3C90-22E4-F64E-B2D4-8EB821458C8C | ad:e3bcdfed | 2.805 GB   | 145280   |
| data22_13p6TeV:DAOD_PHYS.46780328._000028.pool.root.1 | 5B2AEDBB-FE83-9843-B657-B5A29EDC4929 | ad:f955825f | 3.020 GB   | 152526   |
| data22_13p6TeV:DAOD_PHYS.46780328._000029.pool.root.1 | 4C42A01F-1DE5-1D4D-920E-CC36DD148289 | ad:f11d6024 | 2.783 GB   | 136291   |
| data22_13p6TeV:DAOD_PHYS.46780328._000030.pool.root.1 | 0173CA07-E820-DE4E-A495-CAE1108BA51D | ad:380c8a68 | 3.021 GB   | 142922   |
| data22_13p6TeV:DAOD_PHYS.46780328._000031.pool.root.1 | 9F0BB9B7-5BAB-8046-805D-CE1753F4B767 | ad:54d1b77e | 2.997 GB   | 140502   |
| data22_13p6TeV:DAOD_PHYS.46780328._000032.pool.root.1 | 4C17D1DC-78AF-4E4E-8770-523684B30674 | ad:e19acd8c | 3.041 GB   | 143698   |
| data22_13p6TeV:DAOD_PHYS.46780328._000033.pool.root.1 | BE221C30-F45F-5242-923D-EE2D0D9812D8 | ad:46f52461 | 2.739 GB   | 141242   |
| data22_13p6TeV:DAOD_PHYS.46780328._000034.pool.root.1 | 08BDB828-9280-0848-933C-DC72D9CE08CA | ad:d0444f77 | 2.661 GB   | 132148   |
| data22_13p6TeV:DAOD_PHYS.46780328._000035.pool.root.1 | CDE99E43-4256-0B4E-B40F-FCF3E05CAB1F | ad:ff6871e6 | 3.064 GB   | 144379   |
| data22_13p6TeV:DAOD_PHYS.46780328._000036.pool.root.1 | BEDA745A-6D15-8044-8E10-9A0019099F67 | ad:02a90955 | 3.238 GB   | 151651   |
| data22_13p6TeV:DAOD_PHYS.46780328._000037.pool.root.1 | D07E4451-0291-0841-BA89-3BB42C7ED7EB | ad:3dd380ee | 2.692 GB   | 131554   |
| data22_13p6TeV:DAOD_PHYS.46780328._000038.pool.root.1 | D221A8CF-5200-064B-BAE2-5305EB2DB2FB | ad:c116d6f3 | 2.791 GB   | 139828   |
| data22_13p6TeV:DAOD_PHYS.46780328._000039.pool.root.1 | 699BECA3-FB4D-B343-ADE2-82064404CCC4 | ad:539be73f | 2.758 GB   | 138051   |
| data22_13p6TeV:DAOD_PHYS.46780328._000040.pool.root.1 | 05AF3117-9590-DD44-9C28-EB1B0FF8357D | ad:7fd10705 | 2.042 GB   | 101761   |
| data22_13p6TeV:DAOD_PHYS.46780328._000041.pool.root.1 | 57E0D3EC-2760-EB49-8F14-FC3226E0C3B0 | ad:566943dd | 2.365 GB   | 117468   |
| data22_13p6TeV:DAOD_PHYS.46780328._000042.pool.root.1 | 70936FA2-A0A5-2844-9A3E-604FF30A22D7 | ad:6c958ddc | 2.658 GB   | 132357   |
| data22_13p6TeV:DAOD_PHYS.46780328._000043.pool.root.1 | 07AC721A-AEE3-8444-9E6D-94F1C458B55B | ad:01ea4976 | 2.732 GB   | 136289   |
| data22_13p6TeV:DAOD_PHYS.46780328._000044.pool.root.1 | 7AA33FFB-A72B-C944-8909-7BCD07CD52DF | ad:12fa91c5 | 2.748 GB   | 137036   |
| data22_13p6TeV:DAOD_PHYS.46780328._000045.pool.root.1 | B40A0A62-27B8-B54B-95D3-DAE1365C87BA | ad:a1ba43a3 | 2.598 GB   | 129486   |
| data22_13p6TeV:DAOD_PHYS.46780328._000046.pool.root.1 | B20E40B8-30E4-284B-AD87-02F7A9299B0E | ad:a0bba652 | 2.747 GB   | 136946   |
| data22_13p6TeV:DAOD_PHYS.46780328._000047.pool.root.1 | 332614CE-312E-9943-BB75-C101A7E89303 | ad:65fadd6b | 2.731 GB   | 136565   |
| data22_13p6TeV:DAOD_PHYS.46780328._000048.pool.root.1 | 7424D495-5D4A-B143-A76D-62FB707B80D5 | ad:5cc0e5e5 | 2.674 GB   | 133142   |
| data22_13p6TeV:DAOD_PHYS.46780328._000049.pool.root.1 | E1F6C27D-47CA-F74B-8935-52CFDC8CB7BB | ad:2694120c | 2.776 GB   | 137870   |
| data22_13p6TeV:DAOD_PHYS.46780328._000050.pool.root.1 | F9EBF257-9B21-2848-A473-DA86E91936E0 | ad:624f4158 | 2.989 GB   | 140575   |
| data22_13p6TeV:DAOD_PHYS.46780328._000051.pool.root.1 | 6E712B0B-7834-9241-BECB-49ED11127E82 | ad:008214d1 | 2.463 GB   | 115939   |
| data22_13p6TeV:DAOD_PHYS.46780328._000052.pool.root.1 | 8B6A6784-FB71-9241-9857-87B2C1AF0FC8 | ad:8302af41 | 2.465 GB   | 119949   |
| data22_13p6TeV:DAOD_PHYS.46780328._000053.pool.root.1 | F79BE44B-0A37-7E46-AF0F-CDF6AD3E48AA | ad:d57f9a77 | 2.728 GB   | 136383   |
| data22_13p6TeV:DAOD_PHYS.46780328._000054.pool.root.1 | 862565EC-F05B-B841-A616-043D0A92CBB0 | ad:6a85d9a9 | 2.272 GB   | 113160   |
| data22_13p6TeV:DAOD_PHYS.46780328._000055.pool.root.1 | B41385B9-75D1-4B43-A79F-DC3520F75644 | ad:51cd445c | 2.571 GB   | 128438   |
| data22_13p6TeV:DAOD_PHYS.46780328._000056.pool.root.1 | 909C8C2E-E9A4-174D-9F49-4AFCEDA4344B | ad:62be7d19 | 2.830 GB   | 141063   |
| data22_13p6TeV:DAOD_PHYS.46780328._000057.pool.root.1 | 53BF8824-0105-1845-A93D-AB247F432273 | ad:95b3753d | 2.712 GB   | 134945   |
| data22_13p6TeV:DAOD_PHYS.46780328._000058.pool.root.1 | 84B2CE58-13C3-3348-9A00-5BD1A5E42BA5 | ad:d716d3c7 | 2.271 GB   | 128166   |
| data22_13p6TeV:DAOD_PHYS.46780328._000059.pool.root.1 | 2277F284-4FEA-5B44-A825-44E49872EEBC | ad:cc87b9fe | 1.450 GB   | 96612    |
| data22_13p6TeV:DAOD_PHYS.46780328._000060.pool.root.1 | 379E3E02-8AFB-F44C-933D-903D7EFB4651 | ad:b2bfd245 | 1.996 GB   | 132600   |
| data22_13p6TeV:DAOD_PHYS.46780328._000061.pool.root.1 | 090EF4EB-81C9-FB4A-867F-DA318DCD24E3 | ad:414b6e1b | 2.000 GB   | 133111   |
| data22_13p6TeV:DAOD_PHYS.46780328._000062.pool.root.1 | 5F947489-EB6F-D344-A5E6-1AD185F2205C | ad:22eda1ed | 1.949 GB   | 130098   |
| data22_13p6TeV:DAOD_PHYS.46780328._000063.pool.root.1 | BC5E168E-E9DB-EF48-AF46-C60F10547408 | ad:f2d296e3 | 1.786 GB   | 119620   |
| data22_13p6TeV:DAOD_PHYS.46780328._000064.pool.root.1 | 429AD17F-3CA7-C841-89E0-36AB72BD3DFA | ad:00030e3b | 2.088 GB   | 139926   |
| data22_13p6TeV:DAOD_PHYS.46780328._000065.pool.root.1 | 3F649B97-0508-8146-88F4-8904FF3B1A1F | ad:d62aa363 | 1.469 GB   | 98368    |
| data22_13p6TeV:DAOD_PHYS.46780328._000066.pool.root.1 | 1ADF2F42-21AF-5140-B53A-5443AED0D883 | ad:b37396f0 | 2.040 GB   | 136273   |
| data22_13p6TeV:DAOD_PHYS.46780328._000067.pool.root.1 | AF910A57-EFC5-6849-9D86-337F23139D9C | ad:d872af3c | 2.051 GB   | 120748   |
| data22_13p6TeV:DAOD_PHYS.46780328._000068.pool.root.1 | 02C21BA6-C316-1842-81A2-DDAC8875CA46 | ad:f61e623d | 2.573 GB   | 126465   |
| data22_13p6TeV:DAOD_PHYS.46780328._000069.pool.root.1 | 7A3760B3-0190-9D41-9FC5-2BB2810A0EDE | ad:8ed1c03e | 2.633 GB   | 132166   |
| data22_13p6TeV:DAOD_PHYS.46780328._000070.pool.root.1 | 4859B76D-0D3D-354F-BAB5-4B4001AFE2AD | ad:38b28bad | 2.792 GB   | 139423   |
| data22_13p6TeV:DAOD_PHYS.46780328._000071.pool.root.1 | EAA6F914-E978-0149-89EC-7030B36973AD | ad:e6f46bc6 | 2.850 GB   | 140661   |
| data22_13p6TeV:DAOD_PHYS.46780328._000072.pool.root.1 | 36C13974-389C-F841-8AE4-4C7666FF3B5F | ad:48858a6a | 2.143 GB   | 105975   |
| data22_13p6TeV:DAOD_PHYS.46780328._000073.pool.root.1 | A2E2644B-8A89-9A47-A286-1548CB95BD1E | ad:d68f6f60 | 2.729 GB   | 135307   |
| data22_13p6TeV:DAOD_PHYS.46780328._000074.pool.root.1 | ECBB0ED4-B86A-444E-9CC5-D880E01CA7A8 | ad:4f3ae2a4 | 2.563 GB   | 126828   |
| data22_13p6TeV:DAOD_PHYS.46780328._000075.pool.root.1 | 246C63C7-4684-D54A-AD73-036313C6A9B3 | ad:49bd0963 | 2.749 GB   | 136481   |
| data22_13p6TeV:DAOD_PHYS.46780328._000076.pool.root.1 | C5A024A1-BEE7-0247-8487-B35EC8DC9BC5 | ad:7f990253 | 2.418 GB   | 133243   |
| data22_13p6TeV:DAOD_PHYS.46780328._000077.pool.root.1 | 2F41B93C-32AC-F24A-8D36-6A7347713B72 | ad:64752473 | 2.164 GB   | 115323   |
| data22_13p6TeV:DAOD_PHYS.46780328._000078.pool.root.1 | FCBEBE62-41DC-5740-AEDD-607636531AFD | ad:aa72aa76 | 2.673 GB   | 132925   |
| data22_13p6TeV:DAOD_PHYS.46780328._000079.pool.root.1 | 3945E378-2C44-5840-8300-92B54B44EB19 | ad:1f6e5ba4 | 2.550 GB   | 126882   |
| data22_13p6TeV:DAOD_PHYS.46780328._000080.pool.root.1 | F857A8F6-88CC-B940-B050-4197DA10F065 | ad:aa591f79 | 2.688 GB   | 133579   |
| data22_13p6TeV:DAOD_PHYS.46780328._000081.pool.root.1 | 00595C02-352D-F144-A266-83EC0E1D82B9 | ad:fedfbc0f | 2.082 GB   | 103121   |
| data22_13p6TeV:DAOD_PHYS.46780328._000082.pool.root.1 | 3794CE38-1DC4-FD40-9CD5-3E6116A10C9E | ad:a4683d5d | 2.083 GB   | 102738   |
| data22_13p6TeV:DAOD_PHYS.46780328._000083.pool.root.1 | 461C98DA-72F8-464E-BB1C-AC23A442E98E | ad:9df370c6 | 2.707 GB   | 138965   |
| data22_13p6TeV:DAOD_PHYS.46780328._000084.pool.root.1 | 982F160C-B533-2749-B50A-52D8091F6CAE | ad:18d3f438 | 2.396 GB   | 119701   |
| data22_13p6TeV:DAOD_PHYS.46780328._000085.pool.root.1 | 8A63E196-CF2A-114F-B795-15FA0C4A4ED8 | ad:ada41177 | 2.593 GB   | 129581   |
| data22_13p6TeV:DAOD_PHYS.46780328._000086.pool.root.1 | B4865935-CED4-3C40-B3F9-D36EF233920E | ad:a5ff179e | 2.819 GB   | 141292   |
| data22_13p6TeV:DAOD_PHYS.46780328._000087.pool.root.1 | 4C884B1F-B99A-B64E-A14C-1EC7AB208FCC | ad:45a14188 | 2.581 GB   | 129228   |
| data22_13p6TeV:DAOD_PHYS.46780328._000088.pool.root.1 | 88E0B37D-A51F-C445-9510-BBB2D2FCF133 | ad:0c7e7559 | 2.531 GB   | 126083   |
| data22_13p6TeV:DAOD_PHYS.46780328._000089.pool.root.1 | FE1530EC-B34A-704F-89A9-A33FD2C62786 | ad:1f004353 | 2.825 GB   | 139880   |
| data22_13p6TeV:DAOD_PHYS.46780328._000090.pool.root.1 | 2CA4BD0E-2EFF-F54F-A576-8C1A56C999DD | ad:519f2c52 | 2.519 GB   | 124898   |
| data22_13p6TeV:DAOD_PHYS.46780328._000091.pool.root.1 | FE90812F-28B1-A841-88B9-229546E59A9F | ad:66e3ed7e | 2.772 GB   | 137941   |
| data22_13p6TeV:DAOD_PHYS.46780328._000092.pool.root.1 | 720838EC-07DE-2D4E-BBCF-0C60519BAB39 | ad:84098482 | 2.765 GB   | 137586   |
| data22_13p6TeV:DAOD_PHYS.46780328._000093.pool.root.1 | FB8304CE-FC1E-5842-8F99-44B88945F2E4 | ad:e834838a | 2.684 GB   | 133501   |
| data22_13p6TeV:DAOD_PHYS.46780328._000094.pool.root.1 | 79645D85-16D7-9540-ACD6-9764CDB64F92 | ad:2ea5dd7a | 2.787 GB   | 138611   |
| data22_13p6TeV:DAOD_PHYS.46780328._000095.pool.root.1 | 971BDC77-C169-C043-924F-CE559A93DAC0 | ad:a78ce271 | 2.608 GB   | 130472   |
| data22_13p6TeV:DAOD_PHYS.46780328._000096.pool.root.1 | 070DE446-4D03-F242-BBD2-36074C7E0C71 | ad:3a29a7be | 2.529 GB   | 126634   |
| data22_13p6TeV:DAOD_PHYS.46780328._000097.pool.root.1 | 387091A8-9EA7-9243-80EA-BD944993DF00 | ad:bc90550a | 2.272 GB   | 113319   |
| data22_13p6TeV:DAOD_PHYS.46780328._000098.pool.root.1 | DFFC5C13-E98D-F74A-B4AA-6C72721B9A34 | ad:a1bd9e40 | 2.266 GB   | 112858   |
| data22_13p6TeV:DAOD_PHYS.46780328._000099.pool.root.1 | 2052AAEF-8B26-C843-BFF6-2C7B23DBB46F | ad:47ef8cc7 | 2.696 GB   | 133700   |
| data22_13p6TeV:DAOD_PHYS.46780328._000100.pool.root.1 | 6432EF89-CBDE-B24F-9594-C5EC3E834FBA | ad:0b4c9df7 | 2.841 GB   | 140235   |
| data22_13p6TeV:DAOD_PHYS.46780328._000101.pool.root.1 | CF884094-D366-8846-A5C7-3D489E050C0F | ad:94605b01 | 2.731 GB   | 135129   |
| data22_13p6TeV:DAOD_PHYS.46780328._000102.pool.root.1 | 94FA6C05-78BB-5741-8435-9C3B00092DD3 | ad:83242af8 | 2.775 GB   | 138144   |
| data22_13p6TeV:DAOD_PHYS.46780328._000103.pool.root.1 | 044DDE98-5FD4-C24E-84F0-0E926E126078 | ad:d72b75ab | 2.650 GB   | 131946   |
| data22_13p6TeV:DAOD_PHYS.46780328._000104.pool.root.1 | EE92D0A1-57D9-FA41-9526-6CD97310AF22 | ad:25e41068 | 2.728 GB   | 136547   |
| data22_13p6TeV:DAOD_PHYS.46780328._000105.pool.root.1 | BBC9A6A9-CA22-9342-A2B7-3F6602165619 | ad:ddf65fe2 | 2.729 GB   | 136015   |
| data22_13p6TeV:DAOD_PHYS.46780328._000106.pool.root.1 | 35A1C5FB-139D-6048-B843-3AB5403C0E6D | ad:d2ecf268 | 2.610 GB   | 130936   |
| data22_13p6TeV:DAOD_PHYS.46780328._000107.pool.root.1 | E6DD93A4-346B-2245-9CCD-FD4FC1925C09 | ad:b340e44b | 2.778 GB   | 139823   |
| data22_13p6TeV:DAOD_PHYS.46780328._000108.pool.root.1 | 9B0F9C9A-9989-E24F-A1A3-067D3A4E2703 | ad:615c0273 | 2.696 GB   | 139848   |
| data22_13p6TeV:DAOD_PHYS.46780328._000109.pool.root.1 | CBCE7938-7E52-FF43-B7CE-69047864C2F8 | ad:c4c33c05 | 1.995 GB   | 103982   |
| data22_13p6TeV:DAOD_PHYS.46780328._000110.pool.root.1 | 25598AE4-65C2-D349-B021-93668C2D1C32 | ad:59b79709 | 2.187 GB   | 114227   |
| data22_13p6TeV:DAOD_PHYS.46780328._000111.pool.root.1 | 422547C7-5E28-FC4A-B030-26FEB3CE2297 | ad:42ebc4e1 | 2.596 GB   | 135901   |
| data22_13p6TeV:DAOD_PHYS.46780328._000112.pool.root.1 | 575EF8A5-71A5-E748-98A3-1BFFA731A7A1 | ad:111f803f | 1.466 GB   | 76630    |
| data22_13p6TeV:DAOD_PHYS.46780328._000113.pool.root.1 | DAB23F3D-FF06-7C48-A424-A16EABE73402 | ad:2a7e9b92 | 1.527 GB   | 79913    |
| data22_13p6TeV:DAOD_PHYS.46780328._000114.pool.root.1 | C4200F26-ECA8-5948-B122-0CDD82B3F2D6 | ad:3c7ac425 | 1.444 GB   | 75993    |
| data22_13p6TeV:DAOD_PHYS.46780328._000115.pool.root.1 | C8DE0716-7A7D-D54D-B2C2-C5B474AF7C0B | ad:ebaf0a4b | 1.592 GB   | 84252    |
| data22_13p6TeV:DAOD_PHYS.46780328._000116.pool.root.1 | 54118DFC-BA7F-4B45-BAEF-E08158F47371 | ad:f503fae1 | 1.435 GB   | 75734    |
| data22_13p6TeV:DAOD_PHYS.46780328._000117.pool.root.1 | 4B055386-5899-2840-BE8C-FBD82BBF2E3B | ad:32bc0fdb | 1.540 GB   | 76620    |
| data22_13p6TeV:DAOD_PHYS.46780328._000118.pool.root.1 | 0B38DEA3-C395-244A-88BC-A1C8E55D278C | ad:1047d2bf | 1.540 GB   | 76991    |
| data22_13p6TeV:DAOD_PHYS.46780328._000119.pool.root.1 | 3B853655-64A2-5C4D-8EB6-1DAEB6D71FBA | ad:eb2ffcc4 | 1.348 GB   | 67122    |
| data22_13p6TeV:DAOD_PHYS.46780328._000120.pool.root.1 | EAA80545-094F-DE40-AA1E-C50A297A891E | ad:015a79f5 | 1.405 GB   | 70121    |
| data22_13p6TeV:DAOD_PHYS.46780328._000121.pool.root.1 | 30492E4E-83D0-6B4A-B3BC-94B00858AA54 | ad:0c400e38 | 1.243 GB   | 62012    |
| data22_13p6TeV:DAOD_PHYS.46780328._000123.pool.root.1 | 3C1D4527-6EE1-4040-A76D-1885589771C5 | ad:79c2f7a0 | 1.321 GB   | 65879    |
| data22_13p6TeV:DAOD_PHYS.46780328._000124.pool.root.1 | C9064ED2-2FD0-D741-9371-E175E60C0A89 | ad:eb3d3753 | 1.316 GB   | 65616    |
| data22_13p6TeV:DAOD_PHYS.46780328._000125.pool.root.1 | 88FB2D6C-8D1F-D148-95E5-74F55C107E2B | ad:063aed08 | 1.412 GB   | 70567    |
| data22_13p6TeV:DAOD_PHYS.46780328._000126.pool.root.1 | 2096CDA2-D9AA-4240-9A90-DEF30EA567C0 | ad:24d1c15d | 1.326 GB   | 65985    |
| data22_13p6TeV:DAOD_PHYS.46780328._000127.pool.root.1 | F5A1C26D-AFEA-D946-B447-646611EC92E2 | ad:3cbdb917 | 1.318 GB   | 65492    |
| data22_13p6TeV:DAOD_PHYS.46780328._000128.pool.root.1 | 70270312-9985-C244-8FCD-E57E649E1F0A | ad:4c18f8b8 | 1.392 GB   | 69381    |
| data22_13p6TeV:DAOD_PHYS.46780328._000129.pool.root.1 | BF557BF1-FFA4-0647-AB1A-3A42088D0CCC | ad:d72bb391 | 1.418 GB   | 71041    |
| data22_13p6TeV:DAOD_PHYS.46780328._000130.pool.root.1 | 8DC695D0-8B3B-1F4B-BE61-EF0EC3EBD518 | ad:90bfb5a0 | 1.351 GB   | 67552    |
| data22_13p6TeV:DAOD_PHYS.46780328._000131.pool.root.1 | 66C03A80-D557-6A47-AFD6-FEBD52A96963 | ad:448ce984 | 1.307 GB   | 65203    |
| data22_13p6TeV:DAOD_PHYS.46780328._000132.pool.root.1 | C92DD64F-4E93-5449-9177-015E5328C153 | ad:680589bf | 1.408 GB   | 70418    |
| data22_13p6TeV:DAOD_PHYS.46780328._000133.pool.root.1 | FFC3A91C-FAE1-2849-87A2-4C2216B84F48 | ad:5f372955 | 1.306 GB   | 65092    |
| data22_13p6TeV:DAOD_PHYS.46780328._000134.pool.root.1 | 562A0AE0-484E-8742-BE30-36BAC394D241 | ad:e7233e8a | 1.307 GB   | 65232    |
| data22_13p6TeV:DAOD_PHYS.46780328._000135.pool.root.1 | 256268E4-EC24-9946-BB6B-9440FDB6ACBF | ad:f1499c57 | 1.407 GB   | 70294    |
| data22_13p6TeV:DAOD_PHYS.46780328._000136.pool.root.1 | 87958660-1D13-174D-8AFA-58DCEC528CA1 | ad:4ea14510 | 1.254 GB   | 62593    |
| data22_13p6TeV:DAOD_PHYS.46780328._000137.pool.root.1 | F845816A-9C66-3E43-A034-9EACEAD29482 | ad:38114c04 | 894.619 MB | 48739    |
| data22_13p6TeV:DAOD_PHYS.46780328._000138.pool.root.1 | 86CEF5BF-2AA3-A14E-A2D0-18A699A67957 | ad:442fecb4 | 1.483 GB   | 80791    |
| data22_13p6TeV:DAOD_PHYS.46780328._000139.pool.root.1 | F353B43B-3BDD-7C41-A270-E685C3FE0472 | ad:fb7b4121 | 1.466 GB   | 80346    |
| data22_13p6TeV:DAOD_PHYS.46780328._000140.pool.root.1 | C54A375B-88D5-4E49-936B-22694C502D10 | ad:5ffbdce0 | 1.482 GB   | 81096    |
| data22_13p6TeV:DAOD_PHYS.46780328._000141.pool.root.1 | 9DE3C8DF-5527-B34C-837B-DCCED9A255AE | ad:c6c80118 | 1.476 GB   | 80924    |
| data22_13p6TeV:DAOD_PHYS.46780328._000142.pool.root.1 | B409C835-FBD2-4F45-A9D8-25298F948E7A | ad:85d19cf5 | 1.451 GB   | 79779    |
| data22_13p6TeV:DAOD_PHYS.46780328._000143.pool.root.1 | 4B8B5F85-3244-A74E-AC81-6E12E852B6D4 | ad:28882dbe | 1.449 GB   | 79516    |
| data22_13p6TeV:DAOD_PHYS.46780328._000144.pool.root.1 | 829B48C3-39CC-BD45-9201-D3B590EE5349 | ad:8c9ce520 | 1.597 GB   | 87745    |
| data22_13p6TeV:DAOD_PHYS.46780328._000145.pool.root.1 | 3F8E4811-7557-124B-8B0F-A23634EBDF62 | ad:b0d01945 | 1.425 GB   | 78395    |
| data22_13p6TeV:DAOD_PHYS.46780328._000146.pool.root.1 | DE086861-6BE4-AB4D-8DA8-227D83942BCF | ad:de21fa3d | 1.426 GB   | 78569    |
| data22_13p6TeV:DAOD_PHYS.46780328._000147.pool.root.1 | DB5F3A0B-1B12-7641-A1FA-D7E8C7FB3BD5 | ad:b4b53907 | 1.417 GB   | 78028    |
| data22_13p6TeV:DAOD_PHYS.46780328._000148.pool.root.1 | F35902C4-A01E-EC4E-A4DE-8125558354C9 | ad:c29edb4b | 1.411 GB   | 77893    |
| data22_13p6TeV:DAOD_PHYS.46780328._000149.pool.root.1 | 935EC788-A6BA-E14D-989C-93C281DC6D47 | ad:d21e022b | 1.407 GB   | 77352    |
| data22_13p6TeV:DAOD_PHYS.46780328._000150.pool.root.1 | AE36DB9D-FDA9-E544-8B31-CFFB98176BB6 | ad:51336921 | 1.412 GB   | 77989    |
| data22_13p6TeV:DAOD_PHYS.46780328._000151.pool.root.1 | D6C94C22-1AD4-0840-92A0-788BC50CA17F | ad:03f55542 | 1.401 GB   | 77335    |
| data22_13p6TeV:DAOD_PHYS.46780328._000152.pool.root.1 | 5794FAF6-D326-5C4A-B68D-CAC448B9685B | ad:7355393a | 1.385 GB   | 76885    |
| data22_13p6TeV:DAOD_PHYS.46780328._000153.pool.root.1 | D3633787-8BE5-BF40-B836-61F82D5F75ED | ad:0f115816 | 1.392 GB   | 77121    |
| data22_13p6TeV:DAOD_PHYS.46780328._000154.pool.root.1 | 64656F04-A3CB-D548-BA65-C4574B0F57B7 | ad:2ce4ffe7 | 1.398 GB   | 77452    |
| data22_13p6TeV:DAOD_PHYS.46780328._000155.pool.root.1 | F6F67904-433B-914D-849F-321B6452F92A | ad:5f777236 | 1.393 GB   | 76959    |
| data22_13p6TeV:DAOD_PHYS.46780328._000156.pool.root.1 | 4C134E10-26AB-2F4C-9BD2-04DD4FD1F432 | ad:8688e91d | 1.378 GB   | 76341    |
| data22_13p6TeV:DAOD_PHYS.46780328._000157.pool.root.1 | 8581493B-429F-3E45-BFD9-8DFB66C62034 | ad:845ed891 | 828.442 MB | 46077    |
| data22_13p6TeV:DAOD_PHYS.46780328._000158.pool.root.1 | 2A65543D-6804-924C-AF6A-B342E5AE9318 | ad:9659ea5b | 1.496 GB   | 83417    |
| data22_13p6TeV:DAOD_PHYS.46780328._000159.pool.root.1 | 7E02CF4B-720A-BB42-B8A6-2B385B5FAF3D | ad:006c75f6 | 1.361 GB   | 75630    |
| data22_13p6TeV:DAOD_PHYS.46780328._000160.pool.root.1 | 1709C5F5-2F8C-2147-BF81-6639B53D6230 | ad:20f4f69b | 1.296 GB   | 66156    |
| data22_13p6TeV:DAOD_PHYS.46780328._000161.pool.root.1 | 2B92BFFA-7458-3E4F-9250-052705F4CA48 | ad:c673adbf | 1.464 GB   | 74511    |
| data22_13p6TeV:DAOD_PHYS.46780328._000162.pool.root.1 | FF56FC39-C78D-A44E-87BA-6D06C8F7EF5B | ad:3b9e907d | 1.229 GB   | 62680    |
| data22_13p6TeV:DAOD_PHYS.46780328._000163.pool.root.1 | 9DA919FE-FCA8-8544-AF53-7B1464F7D297 | ad:db5618ef | 1.313 GB   | 66972    |
| data22_13p6TeV:DAOD_PHYS.46780328._000164.pool.root.1 | 5336414F-3638-944A-858B-A43FD115D2A3 | ad:185ad2c3 | 1.450 GB   | 74729    |
| data22_13p6TeV:DAOD_PHYS.46780328._000165.pool.root.1 | 7DD4B601-D09E-2647-A231-0DA3656B84A8 | ad:659cb836 | 1.242 GB   | 64460    |
| data22_13p6TeV:DAOD_PHYS.46780328._000166.pool.root.1 | 122C4860-BFA2-B040-AF2B-5BB9B65B958C | ad:4df25d4c | 1.267 GB   | 65144    |
| data22_13p6TeV:DAOD_PHYS.46780328._000167.pool.root.1 | 6011B88D-E2E3-854C-8D50-3C4FF79F9B30 | ad:8ed573f2 | 1.408 GB   | 73384    |
| data22_13p6TeV:DAOD_PHYS.46780328._000168.pool.root.1 | E543230E-7F9E-4544-ADA4-2FE748E6E26E | ad:6982c9bc | 1.220 GB   | 63415    |
| data22_13p6TeV:DAOD_PHYS.46780328._000169.pool.root.1 | 5EB32CB7-E9A0-0149-AD27-FC8A0EAE10D5 | ad:b0ce04a5 | 1.461 GB   | 75269    |
| data22_13p6TeV:DAOD_PHYS.46780328._000170.pool.root.1 | A084F319-3FA7-5E46-9932-4B3F25A3BF36 | ad:895b6622 | 1.302 GB   | 66517    |
| data22_13p6TeV:DAOD_PHYS.46780328._000171.pool.root.1 | 9E76A382-156C-4144-A947-7F10EE8ADEF1 | ad:9a774f89 | 1.217 GB   | 62213    |
| data22_13p6TeV:DAOD_PHYS.46780328._000172.pool.root.1 | CAC163F9-AD3C-3D44-BC0E-AC3D68741AAE | ad:b2ff6d36 | 1.208 GB   | 61857    |
| data22_13p6TeV:DAOD_PHYS.46780328._000173.pool.root.1 | 9AB6530D-E63D-B945-B008-60735129D465 | ad:40d25c71 | 1.448 GB   | 74208    |
| data22_13p6TeV:DAOD_PHYS.46780328._000174.pool.root.1 | 97B21EBA-8619-AC47-9E26-7B948CF9037E | ad:94688d72 | 1.650 GB   | 84816    |
| data22_13p6TeV:DAOD_PHYS.46780328._000175.pool.root.1 | D249ECF9-7DE7-1448-BF26-810FA56B831E | ad:92f5a305 | 1.455 GB   | 74960    |
| data22_13p6TeV:DAOD_PHYS.46780328._000176.pool.root.1 | 032FD1B4-4140-C842-A03F-C1D60B2183A4 | ad:d6d46189 | 1.630 GB   | 84132    |
| data22_13p6TeV:DAOD_PHYS.46780328._000177.pool.root.1 | F1EA6241-1BE8-1F44-AFC2-DA68EB54E660 | ad:eceb2b66 | 1.523 GB   | 78746    |
| data22_13p6TeV:DAOD_PHYS.46780328._000178.pool.root.1 | 7B8260C7-B387-994C-B5BD-2949749BA8A4 | ad:859aafb1 | 1.506 GB   | 76325    |
| data22_13p6TeV:DAOD_PHYS.46780328._000179.pool.root.1 | B050E5E1-BD35-2948-A5AD-47ED831A87C3 | ad:b38fa018 | 1.527 GB   | 79061    |
| data22_13p6TeV:DAOD_PHYS.46780328._000180.pool.root.1 | A1004043-C714-9746-B9C8-CBDEE3B9C22D | ad:fbb12db1 | 1.519 GB   | 78674    |
| data22_13p6TeV:DAOD_PHYS.46780328._000181.pool.root.1 | 657A84E5-DB88-184F-B25B-0AD1F5B1D404 | ad:19c3d618 | 1.155 GB   | 59947    |
| data22_13p6TeV:DAOD_PHYS.46780328._000182.pool.root.1 | 5028E4E5-A689-5C47-B4F8-D2DECB22103E | ad:1149d623 | 1.671 GB   | 88010    |
| data22_13p6TeV:DAOD_PHYS.46780328._000183.pool.root.1 | 36C48297-3843-D440-9EA0-7EACE18C915C | ad:97fe9bdf | 1.666 GB   | 88045    |
| data22_13p6TeV:DAOD_PHYS.46780328._000184.pool.root.1 | 4B6E68D9-BBC1-6D4D-8934-68DF275B47F0 | ad:b8964912 | 1.549 GB   | 82198    |
| data22_13p6TeV:DAOD_PHYS.46780328._000185.pool.root.1 | 8AB64111-6429-9C40-AF2E-5A6E879DDDBF | ad:db346ac3 | 1.615 GB   | 86046    |
| data22_13p6TeV:DAOD_PHYS.46780328._000186.pool.root.1 | 54F38D77-00EA-294F-8831-DA220CBD88F1 | ad:06f144bf | 1.396 GB   | 74517    |
| data22_13p6TeV:DAOD_PHYS.46780328._000187.pool.root.1 | CF9E6F93-ECFA-AE46-8801-0BA90E010253 | ad:581cedec | 1.516 GB   | 79935    |
| data22_13p6TeV:DAOD_PHYS.46780328._000188.pool.root.1 | D983FE85-9633-1C44-A99F-0540F348C3C9 | ad:efa82dad | 1.357 GB   | 71100    |
| data22_13p6TeV:DAOD_PHYS.46780328._000189.pool.root.1 | EC8E6513-5E5D-4141-9012-5C6D0AECA6B6 | ad:3d714378 | 1.572 GB   | 83364    |
| data22_13p6TeV:DAOD_PHYS.46780328._000190.pool.root.1 | C85E98AF-0E3E-BB43-88B5-17FC3AF1D492 | ad:b21d96f1 | 1.631 GB   | 86320    |
| data22_13p6TeV:DAOD_PHYS.46780328._000191.pool.root.1 | 80CC481C-8B54-0648-9FBD-434830D5C630 | ad:34649c08 | 1.598 GB   | 84531    |
| data22_13p6TeV:DAOD_PHYS.46780328._000192.pool.root.1 | CC895E75-0570-F04D-B78D-392A08255C63 | ad:aba85123 | 1.463 GB   | 77298    |
| data22_13p6TeV:DAOD_PHYS.46780328._000193.pool.root.1 | 7895F27E-9494-B840-8708-BA0A20D616AD | ad:bc072868 | 1.651 GB   | 87595    |
| data22_13p6TeV:DAOD_PHYS.46780328._000194.pool.root.1 | 81094863-C6A3-B94C-8F62-3CFC07A4CAA5 | ad:29ce8213 | 1.643 GB   | 86997    |
| data22_13p6TeV:DAOD_PHYS.46780328._000195.pool.root.1 | AC68938F-1699-3E4E-9D6D-847C77DF0E78 | ad:2a8f7aff | 1.609 GB   | 85289    |
| data22_13p6TeV:DAOD_PHYS.46780328._000196.pool.root.1 | C7662054-46DD-714A-845E-33B08FCCD3D0 | ad:735f517f | 1.640 GB   | 87079    |
| data22_13p6TeV:DAOD_PHYS.46780328._000197.pool.root.1 | F8B751BA-F38B-4248-8272-762004A9E4C1 | ad:7cc36525 | 1.634 GB   | 86978    |
| data22_13p6TeV:DAOD_PHYS.46780328._000198.pool.root.1 | 74096DEA-FF59-2C4E-9982-6B786BA941C2 | ad:65c78835 | 1.444 GB   | 77203    |
| data22_13p6TeV:DAOD_PHYS.46780328._000199.pool.root.1 | 76A89B3C-7001-D648-937A-983CC4D829FE | ad:8a3344b0 | 1.587 GB   | 84943    |
| data22_13p6TeV:DAOD_PHYS.46780328._000200.pool.root.1 | 2511B257-2723-7D4D-9EE3-03905E284202 | ad:ba72d964 | 1.605 GB   | 85881    |
| data22_13p6TeV:DAOD_PHYS.46780328._000201.pool.root.1 | D58BEDDC-210D-2248-9920-6C7D2203779F | ad:ad71a448 | 1.611 GB   | 86339    |
| data22_13p6TeV:DAOD_PHYS.46780328._000202.pool.root.1 | D3C6A709-5831-6E45-B0C4-24E3DBBFC401 | ad:fc3700b0 | 1.547 GB   | 82967    |
| data22_13p6TeV:DAOD_PHYS.46780328._000203.pool.root.1 | E52D3BF8-E49F-9D49-95A3-6B6E9890E7DF | ad:8795d3aa | 1.578 GB   | 84766    |
| data22_13p6TeV:DAOD_PHYS.46780328._000204.pool.root.1 | 2B1798A7-F051-CF4F-93AE-485DE0676CFA | ad:bfdf20f6 | 1.583 GB   | 84989    |
| data22_13p6TeV:DAOD_PHYS.46780328._000205.pool.root.1 | 0CB3325C-6F2F-274E-AB20-B66CC38BD638 | ad:7c4a9da3 | 1.576 GB   | 84608    |
| data22_13p6TeV:DAOD_PHYS.46780328._000206.pool.root.1 | FEA240AD-2CDB-9C4E-A431-FE7F72F39C45 | ad:70aaf5cd | 1.563 GB   | 83996    |
| data22_13p6TeV:DAOD_PHYS.46780328._000207.pool.root.1 | 7EDF9A53-A41F-254B-8117-AEA8E5BEC371 | ad:76e9a42a | 1.547 GB   | 83064    |
| data22_13p6TeV:DAOD_PHYS.46780328._000208.pool.root.1 | 7911418E-B64D-D74F-8A7A-0CBB7809EE59 | ad:24fd3732 | 1.547 GB   | 83123    |
| data22_13p6TeV:DAOD_PHYS.46780328._000209.pool.root.1 | 1CEC1E8A-959A-5B4C-9D21-860A8AE5FA10 | ad:5eeba901 | 1.581 GB   | 84088    |
| data22_13p6TeV:DAOD_PHYS.46780328._000210.pool.root.1 | 8812A55D-E5F4-F442-9DAE-DD1D6C672FC4 | ad:578d31ac | 1.577 GB   | 84594    |
| data22_13p6TeV:DAOD_PHYS.46780328._000211.pool.root.1 | 798EC334-B3AE-0643-9D13-583C1D22972A | ad:15b55687 | 1.481 GB   | 83842    |
| data22_13p6TeV:DAOD_PHYS.46780328._000212.pool.root.1 | D9E3B542-1734-CF4D-A318-F4DFAA57E250 | ad:48799d92 | 1.545 GB   | 84652    |
| data22_13p6TeV:DAOD_PHYS.46780328._000213.pool.root.1 | 72B0C2D4-AF01-4F42-8380-DF784A9CE897 | ad:825a4153 | 1.531 GB   | 82768    |
| data22_13p6TeV:DAOD_PHYS.46780328._000214.pool.root.1 | B053AB31-40D6-DE49-AFC1-5063DC7D315C | ad:18415985 | 1.386 GB   | 74891    |
| data22_13p6TeV:DAOD_PHYS.46780328._000215.pool.root.1 | 834AD7B9-B79C-5C4C-8066-DD5A7186DD05 | ad:b9eede26 | 1.508 GB   | 85661    |
| data22_13p6TeV:DAOD_PHYS.46780328._000216.pool.root.1 | 08E83E65-3F70-F44C-B8D1-3917DC6ACA02 | ad:f2972a08 | 1.512 GB   | 84223    |
| data22_13p6TeV:DAOD_PHYS.46780328._000217.pool.root.1 | E0428BD0-A8A8-4C4A-B55C-2539A30050F5 | ad:9fcd11f0 | 1.508 GB   | 81875    |
| data22_13p6TeV:DAOD_PHYS.46780328._000218.pool.root.1 | A2CF243F-BBB1-1F4D-B95D-21DD9E7E45CF | ad:8ce9eafc | 1.398 GB   | 78292    |
| data22_13p6TeV:DAOD_PHYS.46780328._000219.pool.root.1 | 2E9F30AA-967F-AE4A-912F-F2391DBAE94B | ad:ca24119f | 1.326 GB   | 74450    |
| data22_13p6TeV:DAOD_PHYS.46780328._000220.pool.root.1 | 059EC9B2-EBE0-EC4A-B327-3FE0E1E4E1CB | ad:f99ff88e | 1.329 GB   | 74562    |
| data22_13p6TeV:DAOD_PHYS.46780328._000221.pool.root.1 | C3336635-0BAD-1848-8414-FDBFE7844517 | ad:d0250f2b | 2.012 GB   | 100619   |
| data22_13p6TeV:DAOD_PHYS.46780328._000222.pool.root.1 | 1FDF9253-823E-1844-9057-89007AC59D4D | ad:233ff20b | 2.014 GB   | 100972   |
| data22_13p6TeV:DAOD_PHYS.46780328._000223.pool.root.1 | 99822505-89F3-7B40-A63C-2682DD2B3892 | ad:b2cd002b | 2.100 GB   | 105321   |
| data22_13p6TeV:DAOD_PHYS.46780328._000225.pool.root.1 | 82357626-D817-ED48-A953-5C2A27E22970 | ad:509019f1 | 1.949 GB   | 98106    |
| data22_13p6TeV:DAOD_PHYS.46780328._000226.pool.root.1 | B0B59441-EDD9-BE4C-8966-601D53B75DD4 | ad:679ae45f | 2.075 GB   | 104218   |
| data22_13p6TeV:DAOD_PHYS.46780328._000227.pool.root.1 | F49D206F-18BE-2749-8778-6AAE58A4507A | ad:8443d375 | 2.288 GB   | 114877   |
| data22_13p6TeV:DAOD_PHYS.46780328._000228.pool.root.1 | DFFE80C4-81B9-F149-B748-58769B1BEFE9 | ad:70b70daf | 2.077 GB   | 104744   |
| data22_13p6TeV:DAOD_PHYS.46780328._000229.pool.root.1 | F9A329CB-7756-D447-84CF-077765AB109B | ad:39278f2c | 2.006 GB   | 101534   |
| data22_13p6TeV:DAOD_PHYS.46780328._000230.pool.root.1 | D58CD3E2-4001-1140-8FDA-FE62BED85641 | ad:0aa4d735 | 2.029 GB   | 109646   |
| data22_13p6TeV:DAOD_PHYS.46780328._000231.pool.root.1 | 1CAD7327-99CD-C446-B18E-C881FFA95C86 | ad:92ea5d8a | 2.056 GB   | 114992   |
| data22_13p6TeV:DAOD_PHYS.46780328._000232.pool.root.1 | 60AB7A2A-1982-5C45-9A81-C97C2DB3216F | ad:b8458502 | 1.706 GB   | 89147    |
| data22_13p6TeV:DAOD_PHYS.46780328._000233.pool.root.1 | 76C4BE81-1781-7845-B3EF-3A002FFF3328 | ad:747744db | 2.009 GB   | 112777   |
| data22_13p6TeV:DAOD_PHYS.46780328._000234.pool.root.1 | D37D9413-D819-DD47-82EC-EFADC1581BCD | ad:314f0103 | 1.866 GB   | 101028   |
| data22_13p6TeV:DAOD_PHYS.46780328._000235.pool.root.1 | 2716126E-C788-434E-AB5A-E5E83FAB51E1 | ad:c738288d | 1.945 GB   | 98034    |
| data22_13p6TeV:DAOD_PHYS.46780328._000236.pool.root.1 | 9D632852-093E-DD44-9B0A-FFF98B5E5D19 | ad:df0296b1 | 1.930 GB   | 97457    |
| data22_13p6TeV:DAOD_PHYS.46780328._000237.pool.root.1 | 606AF3AF-F529-D141-8A93-3072527587E0 | ad:643cd683 | 1.931 GB   | 97493    |
| data22_13p6TeV:DAOD_PHYS.46780328._000238.pool.root.1 | 7154EDD5-AEA6-0244-B009-0989FA8CD4AF | ad:0763ab0c | 1.909 GB   | 96885    |
| data22_13p6TeV:DAOD_PHYS.46780328._000239.pool.root.1 | 3E6A673F-2D7B-F447-A640-5E1F464E0706 | ad:e0cb9f54 | 1.897 GB   | 96360    |
| data22_13p6TeV:DAOD_PHYS.46780328._000240.pool.root.1 | 51F9C2E9-F930-2641-94A2-EAD4877260D7 | ad:ef066eaf | 1.893 GB   | 96103    |
| data22_13p6TeV:DAOD_PHYS.46780328._000241.pool.root.1 | 2DAB82E9-5AEE-3C4E-94F1-53CC27F5E8F1 | ad:18db458d | 2.162 GB   | 110051   |
| data22_13p6TeV:DAOD_PHYS.46780328._000242.pool.root.1 | E9C6B16D-92EB-0D42-B554-045D73323031 | ad:f3922016 | 2.151 GB   | 109820   |
| data22_13p6TeV:DAOD_PHYS.46780328._000243.pool.root.1 | 4E44B0C4-0F21-4641-8D9E-1A05FD73F6FA | ad:c11e6778 | 1.504 GB   | 81733    |
| data22_13p6TeV:DAOD_PHYS.46780328._000244.pool.root.1 | EACCFE29-8F20-0040-87AF-F12D7AB9038F | ad:a5f66c48 | 1.503 GB   | 81840    |
| data22_13p6TeV:DAOD_PHYS.46780328._000245.pool.root.1 | EE936AF9-88E6-1E49-8F52-58060032B1A0 | ad:f020cb3d | 1.495 GB   | 81773    |
| data22_13p6TeV:DAOD_PHYS.46780328._000246.pool.root.1 | 0F6F22AC-8127-434A-8E9A-ED877B4C0EA8 | ad:a6d4791e | 1.650 GB   | 92460    |
| data22_13p6TeV:DAOD_PHYS.46780328._000247.pool.root.1 | BF15BEBD-E89B-2F49-91DA-9A03A999C808 | ad:6f407212 | 1.685 GB   | 94952    |
| data22_13p6TeV:DAOD_PHYS.46780328._000248.pool.root.1 | 1FB95D22-E557-DD49-BF93-48BFBCF28EFB | ad:d1f3e764 | 1.637 GB   | 92327    |
| data22_13p6TeV:DAOD_PHYS.46780328._000249.pool.root.1 | DCAC794F-FF75-4841-8E22-2676872A1C21 | ad:50c1d25e | 1.303 GB   | 73356    |
| data22_13p6TeV:DAOD_PHYS.46780328._000250.pool.root.1 | 7A2B8D5C-3DAB-5248-8CE5-E0EE406112DA | ad:11483b3f | 1.568 GB   | 88597    |
| data22_13p6TeV:DAOD_PHYS.46780328._000251.pool.root.1 | 524957C6-D386-404B-8BE7-9988139A9C62 | ad:2a4adf4e | 1.475 GB   | 83156    |
| data22_13p6TeV:DAOD_PHYS.46780328._000252.pool.root.1 | D7244558-62EB-B04B-BA47-81ED7668F804 | ad:69ee91de | 1.303 GB   | 73781    |
| data22_13p6TeV:DAOD_PHYS.46780328._000253.pool.root.1 | 392021F3-8395-7F4F-8F51-80B1D8798CC4 | ad:bf46f815 | 1.305 GB   | 73887    |
| data22_13p6TeV:DAOD_PHYS.46780328._000254.pool.root.1 | EACB8C9E-6C3C-2447-B491-8944069895AC | ad:5a7afe5c | 1.298 GB   | 73556    |
| data22_13p6TeV:DAOD_PHYS.46780328._000255.pool.root.1 | 0A9FCC8D-0B1F-D349-BEDD-E1ED64629808 | ad:50f84d48 | 1.285 GB   | 72678    |
| data22_13p6TeV:DAOD_PHYS.46780328._000256.pool.root.1 | E4B90176-9A6A-644F-9D2F-47AB4E4BF9D5 | ad:51316f35 | 1.288 GB   | 73025    |
| data22_13p6TeV:DAOD_PHYS.46780328._000257.pool.root.1 | FD8AEC55-1454-834B-A0C9-85AB4E789518 | ad:12bd46f7 | 1.557 GB   | 88398    |
| data22_13p6TeV:DAOD_PHYS.46780328._000258.pool.root.1 | 69BD17D7-FCFC-7943-ABE3-FC62251F1382 | ad:5b0bcae3 | 1.257 GB   | 71272    |
| data22_13p6TeV:DAOD_PHYS.46780328._000259.pool.root.1 | C520CB9A-4E66-A846-9C26-73C6EA4D603A | ad:db31ea35 | 1.283 GB   | 72762    |
| data22_13p6TeV:DAOD_PHYS.46780328._000260.pool.root.1 | 3328465C-D85B-1D41-ACBE-A51431DB7E68 | ad:77d26aa7 | 1.279 GB   | 72767    |
| data22_13p6TeV:DAOD_PHYS.46780328._000261.pool.root.1 | 2835CC89-1894-7340-B227-DB707474B70B | ad:8b7e1960 | 1.280 GB   | 72717    |
| data22_13p6TeV:DAOD_PHYS.46780328._000262.pool.root.1 | D9372A4B-C4CA-3942-9A1F-D2FF8AAAEC4C | ad:37897828 | 1.271 GB   | 72471    |
| data22_13p6TeV:DAOD_PHYS.46780328._000263.pool.root.1 | 0831EBCC-EA42-1348-A52D-845089EC83C3 | ad:8786f0a2 | 1.273 GB   | 72629    |
| data22_13p6TeV:DAOD_PHYS.46780328._000264.pool.root.1 | CCCF72AA-D538-0145-924B-9DDEE0E57CD1 | ad:43bc6979 | 1.270 GB   | 72321    |
| data22_13p6TeV:DAOD_PHYS.46780328._000265.pool.root.1 | 7D82DDEB-0343-0A47-97BE-5CA2B65B791A | ad:fdb19a24 | 1.249 GB   | 71453    |
| data22_13p6TeV:DAOD_PHYS.46780328._000266.pool.root.1 | CB13E63F-A1AF-4D4E-82FC-28C6C2A585B0 | ad:8fa75834 | 1.258 GB   | 71867    |
| data22_13p6TeV:DAOD_PHYS.46780328._000267.pool.root.1 | 579CCA27-D0DC-FC4E-8C39-6AE200C35076 | ad:9247c15d | 1.558 GB   | 88743    |
| data22_13p6TeV:DAOD_PHYS.46780328._000268.pool.root.1 | 714B4BCE-E3AC-3242-B055-0E0A3037E8A8 | ad:ca604d61 | 922.823 MB | 52565    |
| data22_13p6TeV:DAOD_PHYS.46780328._000269.pool.root.1 | 621D8D4F-AF72-D44C-9798-1CB1ED3D2D4D | ad:69836051 | 1.550 GB   | 88444    |
| data22_13p6TeV:DAOD_PHYS.46780328._000270.pool.root.1 | 8BB4AB26-9E85-964B-B69F-8156B36C128D | ad:70dcfc09 | 929.687 MB | 52747    |
| data22_13p6TeV:DAOD_PHYS.46780328._000271.pool.root.1 | 76A1E10E-CAB4-2345-A9BE-43F41C6869D6 | ad:2b879e3b | 1.838 GB   | 104908   |
| data22_13p6TeV:DAOD_PHYS.46780328._000272.pool.root.1 | 8FC6414F-5373-004A-ABF5-2B50965C559B | ad:c720b027 | 1.819 GB   | 104079   |
| data22_13p6TeV:DAOD_PHYS.46780328._000273.pool.root.1 | CB1AE894-CD4B-D345-B2FB-2719952FC0CE | ad:9b67aa11 | 2.110 GB   | 121057   |
| data22_13p6TeV:DAOD_PHYS.46780328._000274.pool.root.1 | F2EB7F1C-D210-0F49-8FE5-F0AB77EBE4EC | ad:56368cae | 2.104 GB   | 120952   |
| data22_13p6TeV:DAOD_PHYS.46780328._000275.pool.root.1 | 47DECBE1-E024-674D-A7E3-3C48B653646E | ad:a154d379 | 2.086 GB   | 119773   |
| data22_13p6TeV:DAOD_PHYS.46780328._000276.pool.root.1 | 4CA4BAD1-3483-D742-8820-A1F43C4196CB | ad:d2dfc76f | 2.067 GB   | 119046   |
| data22_13p6TeV:DAOD_PHYS.46780328._000277.pool.root.1 | B995C2E4-4088-184B-9850-36D219C1B497 | ad:4e092452 | 1.760 GB   | 101434   |
| data22_13p6TeV:DAOD_PHYS.46780328._000278.pool.root.1 | 2BD9A31B-1A62-234C-BC61-3C3F3D0FF46A | ad:27673b22 | 1.749 GB   | 100989   |
| data22_13p6TeV:DAOD_PHYS.46780328._000279.pool.root.1 | 18D9A74A-699E-EB4C-B478-FC99FD0F1529 | ad:4bc517f6 | 1.720 GB   | 99527    |
| data22_13p6TeV:DAOD_PHYS.46780328._000280.pool.root.1 | 71EA36F7-AF7E-9549-92B0-F4072E46361C | ad:be3a1de7 | 1.718 GB   | 99880    |
| data22_13p6TeV:DAOD_PHYS.46780328._000281.pool.root.1 | 8E8BA687-A587-1146-8DD2-BA368499A2F8 | ad:ed60f05b | 1.728 GB   | 100476   |
| data22_13p6TeV:DAOD_PHYS.46780328._000282.pool.root.1 | EC066A72-C529-B543-969E-E77208E7235E | ad:5b705ea8 | 1.873 GB   | 109682   |
| data22_13p6TeV:DAOD_PHYS.46780328._000283.pool.root.1 | 9E0CF3C1-F39B-DB4A-BC9F-51600E961B82 | ad:ed1b5c25 | 1.664 GB   | 97581    |
| data22_13p6TeV:DAOD_PHYS.46780328._000284.pool.root.1 | B7D4BA0C-3FA4-7A40-B003-228BD0A56FA6 | ad:b4dea83b | 1.674 GB   | 98135    |
| data22_13p6TeV:DAOD_PHYS.46780328._000285.pool.root.1 | 2E5B885E-B122-9B48-A908-3E772160C1F9 | ad:a9d69ded | 1.720 GB   | 101038   |
| data22_13p6TeV:DAOD_PHYS.46780328._000286.pool.root.1 | 8E8A45F6-7DC6-B641-BE1E-B148C6543C6E | ad:97fc4543 | 1.803 GB   | 105866   |
| data22_13p6TeV:DAOD_PHYS.46780328._000287.pool.root.1 | F5484266-C82D-BB45-9338-3AE66F217926 | ad:ca6a94d5 | 1.644 GB   | 96733    |
| data22_13p6TeV:DAOD_PHYS.46780328._000288.pool.root.1 | 9259E20B-B95B-9F4A-8C02-31A450FFE9E1 | ad:087fce28 | 1.630 GB   | 96087    |
| data22_13p6TeV:DAOD_PHYS.46780328._000289.pool.root.1 | D46F74D1-79C2-9B4D-AD68-E508AE876AD3 | ad:35580ea2 | 1.501 GB   | 88367    |
| data22_13p6TeV:DAOD_PHYS.46780328._000290.pool.root.1 | EFCE9D40-24A3-D744-A35E-621A8DE179AE | ad:6933edf0 | 1.680 GB   | 97551    |
| data22_13p6TeV:DAOD_PHYS.46780328._000291.pool.root.1 | 84C3F599-3CFC-6740-B91B-3B18F88AEEF2 | ad:c5cac7c9 | 1.719 GB   | 101523   |
| data22_13p6TeV:DAOD_PHYS.46780328._000292.pool.root.1 | A1786CA0-277A-5F49-8FC4-C1C385DF79D0 | ad:f4d4937b | 1.608 GB   | 94986    |
| data22_13p6TeV:DAOD_PHYS.46780328._000293.pool.root.1 | 0E7B8F62-A15E-954E-B75F-C710F7220426 | ad:f2bae2c8 | 1.590 GB   | 94093    |
| data22_13p6TeV:DAOD_PHYS.46780328._000294.pool.root.1 | 0621E755-E6CB-9741-9B6E-C153F1943F4A | ad:a53472cd | 1.601 GB   | 94709    |
| data22_13p6TeV:DAOD_PHYS.46780328._000295.pool.root.1 | 5669D51B-F539-F74B-ADE9-EB27F6829AC2 | ad:2f57a45a | 1.608 GB   | 98680    |
| data22_13p6TeV:DAOD_PHYS.46780328._000296.pool.root.1 | 36ABF797-E3E2-B74A-B499-89B7E2C9A930 | ad:2c93b831 | 653.386 MB | 36714    |
| data22_13p6TeV:DAOD_PHYS.46780328._000297.pool.root.1 | B6279CDD-CB64-1C4F-A080-8B8C632D3BF3 | ad:b0730c82 | 817.455 MB | 49802    |
| data22_13p6TeV:DAOD_PHYS.46780328._000298.pool.root.1 | FB1F5056-8F80-9544-9531-77D4AEBB5F81 | ad:cfbe6d6b | 846.227 MB | 49865    |
| data22_13p6TeV:DAOD_PHYS.46780328._000299.pool.root.1 | 8DD737D8-0B39-C743-A6B5-169314B1161E | ad:1df5e713 | 838.467 MB | 49766    |
| data22_13p6TeV:DAOD_PHYS.46780328._000300.pool.root.1 | 822272AE-A65D-3C4A-87D4-80555F502603 | ad:48ba8ff3 | 741.422 MB | 43931    |
| data22_13p6TeV:DAOD_PHYS.46780328._000301.pool.root.1 | B46F80B7-FC59-714C-BA1C-CBF1D5C95EEB | ad:20c1bc7c | 867.036 MB | 51284    |
| data22_13p6TeV:DAOD_PHYS.46780328._000302.pool.root.1 | A9517871-24A5-6343-BA05-C80E6A635B69 | ad:f0d073f1 | 843.999 MB | 49830    |
| data22_13p6TeV:DAOD_PHYS.46780328._000303.pool.root.1 | DD9C8C24-AE50-3D4D-91C4-2A08D70316F0 | ad:9e197286 | 731.093 MB | 43453    |
| data22_13p6TeV:DAOD_PHYS.46780328._000304.pool.root.1 | 4A646019-EBFD-6047-BD5E-67ABA5282881 | ad:613a2257 | 826.918 MB | 49140    |
| data22_13p6TeV:DAOD_PHYS.46780328._000305.pool.root.1 | 318E8B01-79D4-584E-9B87-571864E45AA6 | ad:81eeddb5 | 907.185 MB | 54434    |
| data22_13p6TeV:DAOD_PHYS.46780328._000306.pool.root.1 | 8938F940-7D2B-C048-A061-09B56A6A714F | ad:b5404399 | 712.569 MB | 45733    |
| data22_13p6TeV:DAOD_PHYS.46780328._000307.pool.root.1 | D1114662-8D16-1942-9721-603712B7A548 | ad:bf0e0be0 | 820.979 MB | 53137    |
| data22_13p6TeV:DAOD_PHYS.46780328._000308.pool.root.1 | A0C06EB5-C730-DA48-B84D-08B9606868AA | ad:c8ed46be | 806.303 MB | 50258    |
| data22_13p6TeV:DAOD_PHYS.46780328._000309.pool.root.1 | 5A217609-6BBF-1A4F-B896-B5505AA17840 | ad:67afe1d4 | 827.897 MB | 49062    |
| data22_13p6TeV:DAOD_PHYS.46780328._000310.pool.root.1 | 9757ECE6-43DD-5543-A9A4-0A44FA2FEE5D | ad:d1858012 | 727.080 MB | 43169    |
| data22_13p6TeV:DAOD_PHYS.46780328._000311.pool.root.1 | DF605CA3-EC20-2D4D-9DDE-6A07F27991CC | ad:fad92c6e | 827.412 MB | 48872    |
| data22_13p6TeV:DAOD_PHYS.46780328._000312.pool.root.1 | 28E286CE-E147-C946-9715-723E6EEDC44F | ad:22404875 | 810.621 MB | 50358    |
| data22_13p6TeV:DAOD_PHYS.46780328._000313.pool.root.1 | EE91B007-62E0-324B-BE2D-277AEDCD6B6A | ad:c684a17a | 840.677 MB | 51227    |
| data22_13p6TeV:DAOD_PHYS.46780328._000314.pool.root.1 | CBC8FE5A-36D2-B74D-A4F6-77998F7866EA | ad:db1a5fa3 | 959.740 MB | 56926    |
| data22_13p6TeV:DAOD_PHYS.46780328._000315.pool.root.1 | FC79BE2C-2864-B44F-9BA2-965CDE04E390 | ad:4c1c59cc | 809.445 MB | 47995    |
| data22_13p6TeV:DAOD_PHYS.46780328._000316.pool.root.1 | 36091CD2-A0B7-6148-80AD-6D8EC5CD897B | ad:1a7c2027 | 716.054 MB | 42525    |
| data22_13p6TeV:DAOD_PHYS.46780328._000317.pool.root.1 | 06D5A230-E07C-7C45-9706-02503D6209DA | ad:4e3b780e | 877.718 MB | 53248    |
| data22_13p6TeV:DAOD_PHYS.46780328._000318.pool.root.1 | 31547987-1B28-1148-AAEC-1D7F102F3386 | ad:fd7b5bb1 | 805.949 MB | 50387    |
| data22_13p6TeV:DAOD_PHYS.46780328._000319.pool.root.1 | 3B99505F-8A66-D843-8EEC-030F55632A27 | ad:707861b8 | 966.866 MB | 57942    |
| data22_13p6TeV:DAOD_PHYS.46780328._000320.pool.root.1 | D5B49726-B3DD-EA41-A399-2B63EE8ACB8B | ad:ac1dde6d | 802.133 MB | 47765    |
| data22_13p6TeV:DAOD_PHYS.46780328._000321.pool.root.1 | B0B176C4-6F31-7946-9C9C-F692DB2248B7 | ad:be866df8 | 781.128 MB | 48944    |
| data22_13p6TeV:DAOD_PHYS.46780328._000322.pool.root.1 | 28856B4F-058B-BC49-990D-61129666F97B | ad:38dd7bee | 1.717 GB   | 87451    |
| data22_13p6TeV:DAOD_PHYS.46780328._000323.pool.root.1 | C54362CF-C1E6-AF46-9C3A-E3F01FD66561 | ad:a836c17f | 1.635 GB   | 83184    |
| data22_13p6TeV:DAOD_PHYS.46780328._000324.pool.root.1 | 44779A14-2F4B-1840-801A-AFA4E35014BC | ad:a7db5047 | 1.388 GB   | 69657    |
| data22_13p6TeV:DAOD_PHYS.46780328._000325.pool.root.1 | CB3D171C-19CE-CA4D-A5C4-21F434AB3BA6 | ad:8d464fe7 | 1.340 GB   | 66632    |
| data22_13p6TeV:DAOD_PHYS.46780328._000326.pool.root.1 | E3983AEE-8F63-E94C-8F1A-DFD02B386C1F | ad:bd3b239b | 1.458 GB   | 72079    |
| data22_13p6TeV:DAOD_PHYS.46780328._000327.pool.root.1 | 94B895DD-0191-B64E-8A68-B37BBEF919DA | ad:40f380ac | 1.692 GB   | 84713    |
| data22_13p6TeV:DAOD_PHYS.46780328._000328.pool.root.1 | 020FCE09-0076-C04B-A3ED-06E8A78AC43B | ad:1be45461 | 1.369 GB   | 68870    |
| data22_13p6TeV:DAOD_PHYS.46780328._000329.pool.root.1 | 2CD371A6-D85E-324A-B57B-7D0507159AC9 | ad:d9e43ee1 | 1.386 GB   | 69514    |
| data22_13p6TeV:DAOD_PHYS.46780328._000330.pool.root.1 | 7AA6D80E-2F9E-B548-8D01-D1569C6B1F94 | ad:9559d453 | 1.210 GB   | 65436    |
| data22_13p6TeV:DAOD_PHYS.46780328._000331.pool.root.1 | 291EFDF1-CBCF-9248-88C8-EF7856734A40 | ad:076320f7 | 1.073 GB   | 55021    |
| data22_13p6TeV:DAOD_PHYS.46780328._000332.pool.root.1 | B4BDEC24-E0A2-734F-A1F7-84B02B6C2741 | ad:7038ec73 | 1.102 GB   | 56572    |
| data22_13p6TeV:DAOD_PHYS.46780328._000333.pool.root.1 | CE78CBF7-8CA5-994D-9995-E7D639240CB2 | ad:be504838 | 1.654 GB   | 88742    |
| data22_13p6TeV:DAOD_PHYS.46780328._000334.pool.root.1 | 4B9EC8E4-533C-A645-9815-9886ACE1EC25 | ad:904bf3a6 | 790.986 MB | 42452    |
| data22_13p6TeV:DAOD_PHYS.46780328._000335.pool.root.1 | D3623FF9-FC35-F54A-B3FD-69C3457E5D5A | ad:d6e326d1 | 870.779 MB | 50171    |
| data22_13p6TeV:DAOD_PHYS.46780328._000336.pool.root.1 | ADE1DA00-DAAD-824C-BD60-FA9346968115 | ad:1e1755ae | 879.873 MB | 50603    |
| data22_13p6TeV:DAOD_PHYS.46780328._000337.pool.root.1 | DB420442-4651-504A-B963-FE7A84C1697B | ad:02a8b6bc | 730.091 MB | 42077    |
| data22_13p6TeV:DAOD_PHYS.46780328._000338.pool.root.1 | 957BBD7A-A954-3248-AE0F-33F5DDE36E04 | ad:ab1b5d4e | 1.429 GB   | 83048    |
| data22_13p6TeV:DAOD_PHYS.46780328._000339.pool.root.1 | C019BC07-73E9-FB46-A2AD-09DE8CD85199 | ad:4e922197 | 1.141 GB   | 66003    |
| data22_13p6TeV:DAOD_PHYS.46780328._000340.pool.root.1 | BAF98830-6654-CA4F-AE37-BC1BF718617E | ad:f7e0bb4c | 940.822 MB | 54499    |
| data22_13p6TeV:DAOD_PHYS.46780328._000341.pool.root.1 | CB9816BA-6F00-B549-82C7-F95270BDD821 | ad:9f65f946 | 861.296 MB | 50120    |
| data22_13p6TeV:DAOD_PHYS.46780328._000342.pool.root.1 | 9BB08D06-719C-F044-B58D-C2E0A4C9857B | ad:86db1d06 | 1.434 GB   | 78556    |
| data22_13p6TeV:DAOD_PHYS.46780328._000343.pool.root.1 | 712DD3D2-3F64-234D-920A-75CEECB9312F | ad:7f45e122 | 1.338 GB   | 71020    |
| data22_13p6TeV:DAOD_PHYS.46780328._000344.pool.root.1 | 7B20D01E-34CC-304F-9E73-CA34D7D7ABA2 | ad:c2c0d197 | 1.074 GB   | 60997    |
| data22_13p6TeV:DAOD_PHYS.46780328._000345.pool.root.1 | 0B7A2F73-8BF8-DB4F-9609-37E4CBD26E7A | ad:d282f170 | 1.392 GB   | 72489    |
| data22_13p6TeV:DAOD_PHYS.46780328._000346.pool.root.1 | 0E78CB52-AD80-3448-9DC7-8A62BE8CC08C | ad:52cea8d0 | 1.613 GB   | 83208    |
| data22_13p6TeV:DAOD_PHYS.46780328._000347.pool.root.1 | C7E8EDDB-8E0B-B944-9C81-2BECBA8AA58C | ad:09c9253f | 1.510 GB   | 91931    |
| data22_13p6TeV:DAOD_PHYS.46780328._000348.pool.root.1 | 5454D163-56D6-F84F-8FDF-8842253DC7E8 | ad:ea07bd62 | 1.397 GB   | 83576    |
| data22_13p6TeV:DAOD_PHYS.46780328._000349.pool.root.1 | D6C95F3B-6180-9F49-A5EB-4571EA5F1462 | ad:455d472d | 1.876 GB   | 112973   |
| data22_13p6TeV:DAOD_PHYS.46780328._000351.pool.root.1 | 39C0FDC4-A9DF-6346-9ECD-FDFB56F8D7DB | ad:248afe2f | 1.700 GB   | 98499    |
| data22_13p6TeV:DAOD_PHYS.46780328._000352.pool.root.1 | 3EDDD639-446C-2544-B783-9E0009A55808 | ad:7ac093f0 | 1.498 GB   | 87211    |
| data22_13p6TeV:DAOD_PHYS.46780328._000353.pool.root.1 | 402C633B-2694-E944-84D3-9AFC5542DFA6 | ad:595ffe57 | 1.549 GB   | 90537    |
| data22_13p6TeV:DAOD_PHYS.46780328._000355.pool.root.1 | EFEF26CC-29D5-BD4E-9EC5-A2B64B0ECF85 | ad:160b39db | 1.670 GB   | 91462    |
| data22_13p6TeV:DAOD_PHYS.46780328._000357.pool.root.1 | 69A8DC4A-11CB-5F42-995D-6C2860837DB2 | ad:9a91ff71 | 1.797 GB   | 102931   |
| data22_13p6TeV:DAOD_PHYS.46780328._000358.pool.root.1 | DE590361-C429-1842-8040-4418E2F414BC | ad:6f123a6a | 2.072 GB   | 102331   |
| data22_13p6TeV:DAOD_PHYS.46780328._000360.pool.root.1 | E9326288-46B8-D84D-AB86-973B0FF72980 | ad:f1fa40db | 1.459 GB   | 74812    |
| data22_13p6TeV:DAOD_PHYS.46780328._000361.pool.root.1 | 07FEEF26-751D-F841-973B-CA24E9F27B52 | ad:fc569445 | 1.607 GB   | 88139    |
| data22_13p6TeV:DAOD_PHYS.46780328._000362.pool.root.1 | D093E257-FF93-AC49-A86B-F72EE801CDFA | ad:89c84323 | 1.748 GB   | 99451    |
| data22_13p6TeV:DAOD_PHYS.46780328._000363.pool.root.1 | 94EC72B9-EF53-CD44-AA14-91A3EACE2763 | ad:d9b4622a | 1.676 GB   | 92693    |
| data22_13p6TeV:DAOD_PHYS.46780328._000364.pool.root.1 | BEDD2665-5132-FB48-9722-2ADFCD253ED9 | ad:d3320733 | 2.170 GB   | 119491   |
| data22_13p6TeV:DAOD_PHYS.46780328._000365.pool.root.1 | C19284A6-6681-1848-B6EB-AC370B6EDF25 | ad:1d352817 | 1.679 GB   | 94351    |
| data22_13p6TeV:DAOD_PHYS.46780328._000366.pool.root.1 | CF9C6059-85AC-B142-A566-A672969CD307 | ad:ede5dfc2 | 1.704 GB   | 98340    |
| data22_13p6TeV:DAOD_PHYS.46780328._000367.pool.root.1 | D2F3FB8E-137D-6747-B2E2-09A22EF8FEC9 | ad:a01b8fb2 | 2.132 GB   | 119897   |
| data22_13p6TeV:DAOD_PHYS.46780328._000368.pool.root.1 | C3C5ED7C-51A9-6D4F-9902-4DF878840378 | ad:b62b882f | 1.562 GB   | 89321    |
| data22_13p6TeV:DAOD_PHYS.46780328._000369.pool.root.1 | 68EAAF60-6F49-BB4D-9AEE-E5B115690462 | ad:c12464b0 | 1.609 GB   | 90333    |
| data22_13p6TeV:DAOD_PHYS.46780328._000370.pool.root.1 | 6C2986B8-F7CE-C449-AE8C-A9113173018F | ad:cd318a48 | 1.700 GB   | 98074    |
| data22_13p6TeV:DAOD_PHYS.46780328._000371.pool.root.1 | 100D5116-0DB3-FC47-BD4B-8625BD1CC1B0 | ad:a8791f23 | 1.559 GB   | 87893    |
| data22_13p6TeV:DAOD_PHYS.46780328._000373.pool.root.1 | F3B796D5-056E-394C-8175-908401CDE78D | ad:a2a5f91f | 1.654 GB   | 95166    |
| data22_13p6TeV:DAOD_PHYS.46780328._000375.pool.root.1 | 7D0538E9-3D45-E44A-AF93-F85B5BC34356 | ad:62d6d329 | 1.764 GB   | 96606    |
| data22_13p6TeV:DAOD_PHYS.46780328._000377.pool.root.1 | B0C33006-DDE4-7043-9539-AAE4FD9CAB93 | ad:018129e2 | 851.542 MB | 49461    |
| data22_13p6TeV:DAOD_PHYS.46780328._000378.pool.root.1 | ED67CED3-6F5B-434A-8512-D8A658E743F9 | ad:9e6a5083 | 1.769 GB   | 103111   |
| data22_13p6TeV:DAOD_PHYS.46780328._000379.pool.root.1 | 4E702D26-C5B5-BE43-9A2E-7BDFAED1BB1B | ad:9991d041 | 1.854 GB   | 94679    |
| data22_13p6TeV:DAOD_PHYS.46780328._000380.pool.root.1 | 173FDF9C-05A7-0E4A-9999-9BA78C30108E | ad:34c15494 | 1.804 GB   | 89885    |
| data22_13p6TeV:DAOD_PHYS.46780328._000381.pool.root.1 | B08CE520-2233-1F4D-9A83-A115914245D2 | ad:5776bbbc | 1.923 GB   | 95827    |
| data22_13p6TeV:DAOD_PHYS.46780328._000382.pool.root.1 | 6497264B-E8FA-CB4C-A47B-9FE5BB573B52 | ad:e325b927 | 2.068 GB   | 103457   |
| data22_13p6TeV:DAOD_PHYS.46780328._000384.pool.root.1 | 6BBC4746-DDCE-0E41-86CB-FBC99DD999E1 | ad:59c8f4d6 | 1.641 GB   | 87240    |
| data22_13p6TeV:DAOD_PHYS.46780328._000385.pool.root.1 | 171098CE-CEBA-FB49-A4ED-0AD054973952 | ad:82492e0a | 1.728 GB   | 95091    |
| data22_13p6TeV:DAOD_PHYS.46780328._000386.pool.root.1 | 70FF7DA9-6856-E84E-B0A9-EE47244B8C6B | ad:d341cd39 | 1.576 GB   | 92072    |
| data22_13p6TeV:DAOD_PHYS.46780328._000387.pool.root.1 | A6ED4AEF-E77E-824D-BEB5-E24D1A7E9FEE | ad:9a86bf55 | 1.539 GB   | 91291    |
| data22_13p6TeV:DAOD_PHYS.46780328._000388.pool.root.1 | 3B5ECA82-D811-F743-9B20-751EC9E85850 | ad:8f51d09c | 1.258 GB   | 70385    |
| data22_13p6TeV:DAOD_PHYS.46780328._000389.pool.root.1 | 19D05983-94B0-CF4F-94B2-550525F7AC3F | ad:c1ebeac1 | 1.450 GB   | 78407    |
| data22_13p6TeV:DAOD_PHYS.46780328._000390.pool.root.1 | FFC9328E-BE4A-A34B-85CB-3201478002F8 | ad:77d5d431 | 1.460 GB   | 81453    |
| data22_13p6TeV:DAOD_PHYS.46780328._000391.pool.root.1 | 2DE32BBB-8DD5-A74B-BCC8-77AFE0F83C27 | ad:d6a912bc | 1.575 GB   | 91361    |
| data22_13p6TeV:DAOD_PHYS.46780328._000392.pool.root.1 | A53D20AD-F33F-7D49-B052-A7DAAB213C9A | ad:5f2d58c5 | 1.724 GB   | 101064   |
| data22_13p6TeV:DAOD_PHYS.46780328._000393.pool.root.1 | CBFB5EE0-3B0B-1E4A-8634-8965B79641B4 | ad:4f12dcda | 1.459 GB   | 76372    |
| data22_13p6TeV:DAOD_PHYS.46780328._000394.pool.root.1 | 965EFB3C-1E1C-2B4D-8957-98E197FEE9F2 | ad:85d8cece | 1.846 GB   | 91998    |
| data22_13p6TeV:DAOD_PHYS.46780328._000395.pool.root.1 | F277AE7F-FDEB-014F-9CDA-D23E08435524 | ad:b44850c1 | 1.722 GB   | 87301    |
| data22_13p6TeV:DAOD_PHYS.46780328._000396.pool.root.1 | 5BD75626-5486-C64F-9875-DA105C87395D | ad:47d798a1 | 1.889 GB   | 94423    |
| data22_13p6TeV:DAOD_PHYS.46780328._000398.pool.root.1 | C1DCD1D4-88B8-664A-90AC-C941602FF43F | ad:ac5cfac4 | 2.127 GB   | 109183   |
| data22_13p6TeV:DAOD_PHYS.46780328._000399.pool.root.1 | 25F2CFD7-A5BE-3247-92C8-D8FA115E46EB | ad:7865a71d | 1.703 GB   | 92762    |
| data22_13p6TeV:DAOD_PHYS.46780328._000400.pool.root.1 | E6BF4425-E7C3-B343-B421-B77176F475CF | ad:5b0f6f20 | 1.610 GB   | 95114    |
| data22_13p6TeV:DAOD_PHYS.46780328._000401.pool.root.1 | 031983FB-3F37-864E-9000-F59EA01E2B54 | ad:f5b2eb11 | 1.740 GB   | 98226    |
| data22_13p6TeV:DAOD_PHYS.46780328._000402.pool.root.1 | EE3ED822-4BFF-624D-98E7-BE9E33C7B777 | ad:865022f9 | 1.606 GB   | 86901    |
| data22_13p6TeV:DAOD_PHYS.46780328._000403.pool.root.1 | ED92E435-E55A-0448-BF11-606184782E62 | ad:454fe69a | 1.847 GB   | 93987    |
| data22_13p6TeV:DAOD_PHYS.46780328._000404.pool.root.1 | 2DC091D1-B153-2D4D-A117-636001BF5F66 | ad:db36b5ef | 3.227 GB   | 188659   |
| data22_13p6TeV:DAOD_PHYS.46780328._000405.pool.root.1 | 3AFE1DB1-7444-8141-A15F-F31DF4AECF4F | ad:c1300efe | 1.349 GB   | 69575    |
| data22_13p6TeV:DAOD_PHYS.46780328._000407.pool.root.1 | 74C744C5-F4B6-C64A-9105-A9138448726B | ad:78a7b3ea | 1.327 GB   | 65931    |
+-------------------------------------------------------+--------------------------------------+-------------+------------+----------+
'''

In [ ]:
# Convert the raw `data22_str` table text into a DataFrame
# The input contains header/footer lines, separator rows, and data rows.
# Expected columns are: SCOPE:NAME, GUID, ADLER32, FILESIZE, EVENTS.
def parse_data22_str_to_df(data22_str: str) -> pd.DataFrame:
    lines = [line.strip() for line in data22_str.splitlines()]
    rows = []

    for line in lines:
        if not line:
            continue
        if line.startswith('+'):
            continue
        if line.startswith('|'):
            cells = [cell.strip() for cell in line.strip('|').split('|')]
            if len(cells) != 5:
                continue
            if cells[0] == 'SCOPE:NAME':
                continue
            if cells[0].startswith('data22_'):
                rows.append(cells)

    df = pd.DataFrame(rows, columns=['SCOPE:NAME', 'GUID', 'ADLER32', 'FILESIZE', 'EVENTS'])
    df['EVENTS'] = pd.to_numeric(df['EVENTS'], errors='coerce').astype('Int64')
    return df


def add_filesize_gb_column(df: pd.DataFrame) -> pd.DataFrame:
    def filesize_to_gb(value: str) -> float:
        if isinstance(value, str):
            parts = value.strip().split()
            if len(parts) == 2:
                number, unit = parts
                try:
                    number = float(number)
                except ValueError:
                    return float('nan')
                unit = unit.upper()
                if unit == 'GB':
                    return number
                if unit == 'MB':
                    return number / 1000
        return float('nan')

    df['FILESIZE [GB]'] = df['FILESIZE'].apply(filesize_to_gb)
    return df

In [29]:
data22_df = parse_data22_str_to_df(data22_str)
add_filesize_gb_column(data22_df)
print(f'Total memory: {data22_df["FILESIZE [GB]"].sum()} GB')
print(f'Total events: {data22_df["EVENTS"].sum() / 1000}k')

Total memory: 683.7770700000001 GB
Total events: 36631.544k

In [ ]:
data22_df_subset = data22_df.sample(n=9, random_state=24)
print(f'Total memory: {data22_df_subset["FILESIZE [GB]"].sum()} GB')
print(f'Total events: {data22_df_subset["EVENTS"].sum() / 1000}k')
# Sort data22_df_subset by index to maintain original order
data22_df_subset.sort_index()

Total memory: 16.187918 GB
Total events: 863.602k

,SCOPE:NAME,GUID,ADLER32,FILESIZE,EVENTS,FILESIZE [GB]
19,data22_13p6TeV:DAOD_PHYS.46780328._000022.pool...,B0252B95-5D1F-0B41-B9A8-AAC666F8ECAE,ad:55a5b803,2.794 GB,139102,2.794000
25,data22_13p6TeV:DAOD_PHYS.46780328._000028.pool...,5B2AEDBB-FE83-9843-B657-B5A29EDC4929,ad:f955825f,3.020 GB,152526,3.020000
179,data22_13p6TeV:DAOD_PHYS.46780328._000183.pool...,36C48297-3843-D440-9EA0-7EACE18C915C,ad:97fe9bdf,1.666 GB,88045,1.666000
211,data22_13p6TeV:DAOD_PHYS.46780328._000215.pool...,834AD7B9-B79C-5C4C-8066-DD5A7186DD05,ad:b9eede26,1.508 GB,85661,1.508000
252,data22_13p6TeV:DAOD_PHYS.46780328._000257.pool...,FD8AEC55-1454-834B-A0C9-85AB4E789518,ad:12bd46f7,1.557 GB,88398,1.557000
299,data22_13p6TeV:DAOD_PHYS.46780328._000304.pool...,4A646019-EBFD-6047-BD5E-67ABA5282881,ad:613a2257,826.918 MB,49140,0.826918
342,data22_13p6TeV:DAOD_PHYS.46780328._000347.pool...,C7E8EDDB-8E0B-B944-9C81-2BECBA8AA58C,ad:09c9253f,1.510 GB,91931,1.510000
351,data22_13p6TeV:DAOD_PHYS.46780328._000360.pool...,E9326288-46B8-D84D-AB86-973B0FF72980,ad:f1fa40db,1.459 GB,74812,1.459000
389,data22_13p6TeV:DAOD_PHYS.46780328._000403.pool...,ED92E435-E55A-0448-BF11-606184782E62,ad:454fe69a,1.847 GB,93987,1.847000

In [28]:
data22_df_subset_DIDs = list(data22_df_subset['SCOPE:NAME'].sort_index())
for DID in data22_df_subset_DIDs:
    print(DID)

data22_13p6TeV:DAOD_PHYS.46780328._000022.pool.root.1
data22_13p6TeV:DAOD_PHYS.46780328._000028.pool.root.1
data22_13p6TeV:DAOD_PHYS.46780328._000183.pool.root.1
data22_13p6TeV:DAOD_PHYS.46780328._000215.pool.root.1
data22_13p6TeV:DAOD_PHYS.46780328._000257.pool.root.1
data22_13p6TeV:DAOD_PHYS.46780328._000304.pool.root.1
data22_13p6TeV:DAOD_PHYS.46780328._000347.pool.root.1
data22_13p6TeV:DAOD_PHYS.46780328._000360.pool.root.1
data22_13p6TeV:DAOD_PHYS.46780328._000403.pool.root.1

Select 9 samples randomly from `data22`

In [12]:
import random

# Select 9 lines with 'data22' from the data22 string representation
data22_subset = random.sample([line for line in data22_str.splitlines() if 'data22' in line] * 5, 9)
data22_subset

['| data22_13p6TeV:DAOD_PHYS.46780328._000130.pool.root.1 | 8DC695D0-8B3B-1F4B-BE61-EF0EC3EBD518 | ad:90bfb5a0 | 1.351 GB   | 67552    |',
 '| data22_13p6TeV:DAOD_PHYS.46780328._000263.pool.root.1 | 0831EBCC-EA42-1348-A52D-845089EC83C3 | ad:8786f0a2 | 1.273 GB   | 72629    |',
 '| data22_13p6TeV:DAOD_PHYS.46780328._000207.pool.root.1 | 7EDF9A53-A41F-254B-8117-AEA8E5BEC371 | ad:76e9a42a | 1.547 GB   | 83064    |',
 '| data22_13p6TeV:DAOD_PHYS.46780328._000116.pool.root.1 | 54118DFC-BA7F-4B45-BAEF-E08158F47371 | ad:f503fae1 | 1.435 GB   | 75734    |',
 '| data22_13p6TeV:DAOD_PHYS.46780328._000105.pool.root.1 | BBC9A6A9-CA22-9342-A2B7-3F6602165619 | ad:ddf65fe2 | 2.729 GB   | 136015   |',
 '| data22_13p6TeV:DAOD_PHYS.46780328._000145.pool.root.1 | 3F8E4811-7557-124B-8B0F-A23634EBDF62 | ad:b0d01945 | 1.425 GB   | 78395    |',
 '| data22_13p6TeV:DAOD_PHYS.46780328._000199.pool.root.1 | 76A89B3C-7001-D648-937A-983CC4D829FE | ad:8a3344b0 | 1.587 GB   | 84943    |',
 '| data22_13p6TeV:DAOD_PHYS.46780328._000283.pool.root.1 | 9E0CF3C1-F39B-DB4A-BC9F-51600E961B82 | ad:ed1b5c25 | 1.664 GB   | 97581    |',
 '| data22_13p6TeV:DAOD_PHYS.46780328._000314.pool.root.1 | CBC8FE5A-36D2-B74D-A4F6-77998F7866EA | ad:db1a5fa3 | 959.740 MB | 56926    |']

In [31]:
data22_subset_cutflow_str = '''|              |#==0          |#==1        |#==2        |#==3          |
------------------------------------------------------------------------
|All           |69.000000 (69)|0.000000 (0)|0.000000 (0)|0.000000 (0)  |
|Cleaning      |69.000000 (69)|0.000000 (0)|0.000000 (0)|0.000000 (0)  |
|PrimaryVertex |69.000000 (69)|0.000000 (0)|0.000000 (0)|0.000000 (0)  |
|Trigger       |69.000000 (69)|0.000000 (0)|0.000000 (0)|0.000000 (0)  |
|SFOS          |0.000000 (0)  |1.000000 (1)|5.000000 (5)|24.000000 (24)|
|NotOverlaps   |0.000000 (0)  |1.000000 (1)|5.000000 (5)|24.000000 (24)|
|Kinematic     |0.000000 (0)  |1.000000 (1)|4.000000 (4)|4.000000 (4)  |
|TriggerMatched|0.000000 (0)  |1.000000 (1)|4.000000 (4)|4.000000 (4)  |
|DeltaR        |0.000000 (0)  |0.000000 (0)|2.000000 (2)|1.000000 (1)  |
|MuType        |0.000000 (0)  |0.000000 (0)|2.000000 (2)|1.000000 (1)  |
------------------------------------------------------------------------'''

In [33]:
data22_subset_cutflow_df = cf.simplify_ZdZdPP_cutflow(cf.str_to_df_ZdZdPP(data22_subset_cutflow_str))
data22_subset_cutflow_df

,Cuts,weights_4e,events_4e,weights_2e2m,events_2e2m,weights_4m,events_4m,weights_All,events_All
0,All,0.0,0,0.0,0,0.0,0,69.0,69
1,Cleaning,0.0,0,0.0,0,0.0,0,69.0,69
2,PrimaryVertex,0.0,0,0.0,0,0.0,0,69.0,69
3,Trigger,0.0,0,0.0,0,0.0,0,69.0,69
4,SFOS,1.0,1,5.0,5,24.0,24,30.0,30
5,NotOverlaps,1.0,1,5.0,5,24.0,24,30.0,30
6,Kinematic,1.0,1,4.0,4,4.0,4,9.0,9
7,TriggerMatched,1.0,1,4.0,4,4.0,4,9.0,9
8,DeltaR,0.0,0,2.0,2,1.0,1,3.0,3
9,MuType,0.0,0,2.0,2,1.0,1,3.0,3

In [35]:
cf.make_spreadsheet(cutflow_dir + '2026-03-30_data22_ZdZdPP.xlsx', {'data22_subset': data22_subset_cutflow_df})